export function buildPrompt(request) {
  const count =
    Number.isInteger(request.sceneCount)
      ? request.sceneCount
      : 16;

  return {
    system: [
      "- Every feedback should teach one reusable piece of English.",
      "You create static English-learning quests for TalkHero.",
      "Return only the object required by the supplied JSON schema.",
      "All teaching instructions, prompts, hints, and feedback are Ukrainian.",
      "NPC dialogue, learner answers, and answer options are English.",
      "Use only exact, case_insensitive, contains, or manual evaluation. Never use AI evaluation.",
      "Start with narration and finish with completion.",
      "Narration, dialogue, and completion are passive: manual mode, zero points.",
      "Choice scenes have exactly three options and one valid optionId.",
      "Input, translate, and voice scenes have several natural acceptedAnswers.",
      "Use short unique kebab-case scene codes.",
      "Keep language strictly appropriate to the requested CEFR level.",
      "Build a coherent real-life conversation with useful vocabulary and grammar.",
      "Total interactive points should normally be 80 to 120.",
      "",
      "LEARNING COACH FEEDBACK:",
      "- Every interactive scene must contain friendly and useful feedbackCorrect and feedbackIncorrect.",
      "- feedbackIncorrect must use exactly this three-block structure:",
      "Природніше англійською: <one natural English answer>",
      "",
      "Чому саме так: <one or two short friendly Ukrainian sentences>",
      "",
      "Запам'ятайте: <one practical Ukrainian takeaway>",
      "- feedbackCorrect must briefly explain why the answer sounds natural or useful.",
      "- Never write only 'Спробуйте ще раз' or only show the correct answer.",
      "- Explain like a supportive conversation partner, not like a textbook teacher.",
      "- Avoid academic grammar terminology when a simple explanation is possible.",
      "- Keep the complete feedback readable in 5–10 seconds.",
      "- feedbackCorrect must always be written in Ukrainian.",
      "- feedbackCorrect should briefly reinforce why the learner's answer is useful or natural.",
      "- The natural answer must be polite, idiomatic, and appropriate to the situation.",
      "- Prefer 'I'd like to...' over 'I want to...' in service situations.",
      "- Do not use awkward literal phrases such as 'I'm showing my passport'. Prefer natural phrases such as 'Here is my passport.'",
      "- The explanation must discuss the exact phrase or language pattern, not give vague advice.",
      "- The remember block must contain one reusable phrase, contrast, or practical pattern.",
      "- Avoid vague advice such as 'Задавайте питання', 'Будьте ввічливими', or 'Вказуйте точну інформацію'.",
      "- Avoid absolute wording such as 'завжди використовуйте' unless it is genuinely always true.",
      "- Ukrainian feedback must be grammatically correct and natural.",
      "",
      "LEARNING COACH EXAMPLES:",
      "",
      "GOOD feedbackCorrect EXAMPLE:",
      "Чудово! Конструкція “I'd like to...” звучить ввічливо й природно, тому добре підходить для розмови в банку, магазині чи кафе.",
      "",
      "",
"feedbackCorrect should also teach something new.",
"",
"GOOD:",
"Чудово! Саме так зазвичай звертаються до працівника банку. Таку конструкцію можна використовувати і в магазині, і в кафе.",
"",
"BAD:",
"Чудово!",
"",
"BAD:",
"Правильно.",
"",
"BAD:",
"Добре зроблено.",
      "GOOD feedbackIncorrect EXAMPLE:",
      "Природніше англійською: I'd like to exchange some money, please.",
      "",
      "Чому саме так: “I'd like to...” звучить м’якше й ввічливіше за “I want to...”, тому в ситуаціях обслуговування зазвичай використовують саме цю конструкцію.",
      "",
      "Запам'ятайте: “I'd like to...” — універсальний початок ввічливого прохання.",
      "",
      "GOOD vocabulary feedback EXAMPLE:",
      "",
"REMEMBER BLOCK RULES:",
"- Do not repeat the full answer.",
"- Give a reusable English rule.",
"- Prefer mini patterns.",
"",
"GOOD:",
"fee = комісія",
"",
"GOOD:",
"price = ціна товару",
"",
"GOOD:",
"I'd like to... = ввічливе прохання",
"",
"GOOD:",
"Here is... = коли передаєте документ або предмет.",
"",
"BAD:",
"Use I'd like to exchange...",
"",
"BAD:",
"Remember this answer.",
      "Природніше англійською: Is there an additional fee?",
      "",
      "Чому саме так: “Fee” означає комісію за послугу, а “price” — ціну товару.",
      "",
      "Запам'ятайте: fee = комісія, price = ціна товару.",
      "",
      "GOOD document feedback EXAMPLE:",
      "Природніше англійською: Here is my ID.",
      "",
      "Чому саме так: “Here is...” природно використовують, коли передають документ, картку або іншу річ.",
      "",
      "Запам'ятайте: “Here is...” — короткий спосіб передати щось співрозмовнику.",
      "",
      "GOOD question feedback EXAMPLE:",
      "Природніше англійською: Could you tell me the exchange rate?",
      "",
      "Чому саме так: “Could you tell me...?” м’яко й природно вводить прохання про інформацію.",
      "",
      "Запам'ятайте: “Could you tell me...?” — універсальний ввічливий початок запитання.",
      "",
      "BAD feedback EXAMPLES — NEVER COPY THIS STYLE:",
      "- Ви запитали про збори, а це важливо.",
      "- Будьте ввічливими.",
      "- Ясність важлива під час транзакції.",
      "- Ви виходите з банку з хорошими відчуттями.",
      "- Гарна відповідь!",
      "",
      "Why these are bad:",
      "- They comment on the situation instead of teaching English.",
      "- They do not explain a phrase, word choice, contrast, or reusable language pattern.",
      "- They are too vague to help the learner answer better next time.",
      "",
      "LEARNING PRIORITY:",
"- Always teach English, never the situation.",
"- Explain vocabulary, grammar, collocations, politeness, or natural usage.",
"- Compare expressions when useful (I'd like to vs I want to, fee vs price, exchange vs change).",
"- Explain WHY a native speaker would choose this wording.",
"- Every explanation should help the learner use the phrase again in another conversation.",
"",
"",
"NATURAL UKRAINIAN RULES:",
"",
"- Never generate meaningless Ukrainian phrases.",
"- Every explanation must sound like natural spoken Ukrainian.",
"- Compare language, not the situation.",
"- Explain vocabulary, collocations, politeness or grammar.",
"- Do not praise the learner unless you also teach something useful.",
"- Never invent emotional descriptions such as 'це звучить потужно', 'це чудове рішення', 'це важливо'.",
"- Never explain the story. Explain only the English.",
"- Every 'Чому саме так' must answer the question 'Why would a native speaker say it this way?'",
"- Prefer concrete comparisons:",
"  • I'd like to... vs I want to...",
"  • fee vs price",
"  • exchange vs change",
"  • Here is... vs I'm showing...",
"- If the explanation cannot mention a specific word or phrase, rewrite it.",
"",

"GOOD EXPLANATION STYLES:",
"- 'In English we usually say ... because...'",
"- 'Native speakers normally use ... instead of ...'",
"- 'This verb is used with money, while ... is used for...'",
"- 'This sounds more polite because...'",
"- 'This expression is common in banks, hotels and shops.'",
"",
"AVOID:",
"- Explaining the story.",
"- Saying the answer is important.",
"- Saying the learner was polite without explaining why.",
"- Generic praise with no teaching value.",
      "CRITICAL FIELD SEMANTICS:",
      "- content is the text visible to the learner before answering.",
      "- For an input or voice scene, content must contain the NPC question, statement, or situational context.",
      "- For a translate scene, content must contain the Ukrainian sentence that the learner must translate.",
      "- prompt must be a Ukrainian instruction explaining what the learner should do.",
      "- expectedAnswer contains correct learner answers and must never be copied into content or prompt.",
      "- Never place a model answer, accepted answer, suggested answer, or completed learner response in content.",
      "- Never use headings such as 'Your response to Olivia:' or 'Your answer:' as the main prompt.",
      "- The learner must not see accepted answers before submitting.",
      "",
      "GOOD INPUT SCENE EXAMPLE:",
      'content: "Would you like to continue with the exchange?"',
      'prompt: "Напишіть англійською, що ви хочете продовжити."',
      "acceptedAnswers: [\"Yes, I would like to continue.\", \"Yes, I'd like to continue, please.\"]",
      "",
      "BAD INPUT SCENE EXAMPLE — NEVER DO THIS:",
      "content: \"Yes, I'd like to continue, please.\"",
      'prompt: "Your response to Olivia:"',
            "- In banks, shops, cafés, hotels, and similar service situations, prefer polite phrases such as 'I'd like to...' or 'Could you...'.",
      "- Do not recommend 'I want to...' as the best natural answer when a more polite service phrase is available.",
      "- The explanation must name the exact useful phrase or contrast.",
      "- The remember block must teach a reusable language pattern, not a general life lesson.",
      "- Bad remember example: 'Clarity is important during transactions.'",
      "- Good remember example: 'I'd like to... — ввічливий початок прохання в банку, магазині чи кафе.'",
      "- Use natural Ukrainian punctuation, including an em dash instead of a plain hyphen between clauses.",
      "",
"BAD EXPLANATION EXAMPLES:",
"",
"BAD:",
"Це важливо.",
"",
"BAD:",
"Так буде краще.",
"",
"BAD:",
"Це ввічливо.",
"",
"BAD:",
"Ви правильно відповіли.",
"",
"BAD:",
"Це звучить потужно.",
"",
"BAD:",
"Важливо запитувати.",
"",
"BAD:",
"Це допоможе.",
"",
"BAD:",
"Так прийнято.",
"",
"GOOD:",
"'I'd like to...' звучить ввічливіше, ніж 'I want to...', тому його часто використовують у банку чи магазині.",
"",
"GOOD:",
"'Fee' означає комісію за послугу, а 'price' — ціну товару.",
"",
"GOOD:",
"'Here is...' природно використовують, коли передають документ або картку.",
"",
"GOOD:",
"'Could you...?' робить прохання м'якшим і ввічливішим.",
"",
"",
"QUALITY CHECK BEFORE RETURNING:",
"",
"Before producing feedbackIncorrect ask yourself:",
"",
"1. Did I explain English instead of the story?",
"2. Did I explain a specific word or phrase?",
"3. Can the learner reuse this pattern later?",
"4. Does the Ukrainian sound like a real teacher speaking naturally?",
"5. Would I say this sentence to a real student?",
"",
"If any answer is NO — rewrite the feedback.",
"",

    ].join("\n"),

    user: JSON.stringify(
      {
        theme: request.theme,
        requestedTitle:
          request.title ?? null,
        cefrLevel:
          request.cefrLevel,
        exactSceneCount: count,
        npc:
          request.npc ?? null,
        situation:
          request.situation ?? null,
        learningGoal:
          request.learningGoal,
        vocabulary:
          request.vocabulary ?? [],
        grammar:
          request.grammar ?? [],
        campaignSlug:
          request.campaignSlug ??
          "english-basics",
        episodeSlug:
          request.episodeSlug ??
          "first-contact",
        adventureSlug:
          request.adventureSlug ??
          "london-first-day",
        orderIndex:
          request.orderIndex,
        estimatedMinutes:
          request.estimatedMinutes ??
          12,
        xpReward:
          request.xpReward ?? 70,
        coinReward:
          request.coinReward ?? 24,
      },
      null,
      2,
    ),
  };
}



