-- Generated by TalkHero Quest Authoring System v1

-- Generated quest: At the Bank
do $$
declare
  campaign_uuid uuid;
  episode_uuid uuid;
  quest_uuid uuid;
  act_uuid uuid;
begin
  select id into campaign_uuid from public.quest_campaigns
  where slug = 'english-basics' and status = 'published';
  if campaign_uuid is null then raise exception 'Campaign not found: english-basics'; end if;

  select id into episode_uuid from public.quest_episodes
  where campaign_id = campaign_uuid and slug = 'first-contact' and status = 'published';
  if episode_uuid is null then raise exception 'Episode not found: first-contact'; end if;

  select id into quest_uuid from public.quests
  where episode_id = episode_uuid and slug = 'bank';

  if quest_uuid is null then
    insert into public.quests (
      episode_id, slug, title, description, quest_type, cefr_level,
      order_index, estimated_minutes, xp_reward, coin_reward, status, config, metadata
    ) values (
      episode_uuid, 'bank', 'At the Bank', 'Complete a simple currency-exchange transaction politely and understand the key conditions.',
      'conversation', 'A2', 6, 12,
      75, 25, 'published', '{"version":1,"sceneCount":13,"staticTest":true,"generated":true}'::jsonb, '{"templateCategory":"static","staticTest":true,"staticQuest":true,"generatedBy":"TalkHero Quest Authoring System v1","adventure":"london-first-day","location":"London"}'::jsonb
    ) returning id into quest_uuid;
  else
    update public.quests set
      title='At the Bank', description='Complete a simple currency-exchange transaction politely and understand the key conditions.', quest_type='conversation',
      cefr_level='A2', order_index=6,
      estimated_minutes=12, xp_reward=75, coin_reward=25,
      status='published', config='{"version":1,"sceneCount":13,"staticTest":true,"generated":true}'::jsonb,
      metadata=coalesce(metadata,'{}'::jsonb)||'{"templateCategory":"static","staticTest":true,"staticQuest":true,"generatedBy":"TalkHero Quest Authoring System v1","adventure":"london-first-day","location":"London"}'::jsonb, updated_at=now()
    where id=quest_uuid;
  end if;

  select id
  into act_uuid
  from public.quest_acts
  where quest_id = quest_uuid
  order by order_index
  limit 1;

  if act_uuid is null then
    insert into public.quest_acts (
      quest_id,
      act_code,
      title,
      description,
      order_index,
      status,
      checkpoint,
      metadata
    ) values (
      quest_uuid,
      'bank-transaction',
      'Bank Transaction',
      'Engage in a conversation at the bank to exchange currency.',
      0,
      'published',
      false,
      '{"generated":true}'::jsonb
    )
    returning id into act_uuid;
  else
    update public.quest_acts
    set
      act_code = 'bank-transaction',
      title = 'Bank Transaction',
      description = 'Engage in a conversation at the bank to exchange currency.',
      order_index = 0,
      status = 'published',
      updated_at = now()
    where id = act_uuid;
  end if;

  delete from public.quest_scenes where quest_id=quest_uuid;

  insert into public.quest_scenes (
    quest_id, act_id, scene_code, order_index, scene_type, speaker,
    content, prompt, options, expected_answer, next_scene_code,
    branching, evaluation_config, metadata
  ) values
  (
    quest_uuid, act_uuid, 'start-narration', 0, 'narration',
    null, 'You walk into the bank in London. The atmosphere is busy but calm. You approach the clerk named Olivia.', null,
    '[]'::jsonb, null,
    'greet-dialogue', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"learner","avatar":"🧑‍💼","emotion":"neutral","goal":"complete the bank transaction","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'greet-dialogue', 1, 'dialogue',
    'Olivia', 'Hello! How can I help you today?', null,
    '[]'::jsonb, null,
    'exchange-input', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Olivia","avatar":"🏦","emotion":"cheerful","goal":"assist the customer","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'exchange-input', 2, 'input',
    null, 'Hello! How can I help you today?', 'Напишіть англійською, що ви хочете обміняти гроші.',
    '[]'::jsonb, '{"acceptedAnswers":["I''d like to exchange some money, please."]}'::jsonb,
    'ask-fee-dialogue', '{}'::jsonb,
    '{"mode":"case_insensitive","points":1,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Чудово! Фраза \"I''d like to exchange...\" звучить ввічливо і природно, тому чудово підходить для розмови в банку.","feedbackIncorrect":"Природніше англійською: I''d like to exchange some money, please.\n\nЧому саме так: \"I''d like to...\" звучить мякіше й ввічливіше, ніж \"I want to...\", тому зазвичай використовується в ситуаціях обслуговування.\n\nЗапам''ятайте: \"I''d like to...\" — ввічливий початок прохання в банку."}'::jsonb, '{"role":"learner","avatar":"🧑‍💼","emotion":"neutral","goal":"ask for exchange","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'ask-fee-dialogue', 3, 'dialogue',
    'Olivia', 'Sure! What currency do you want to exchange, and do you want to know the fee?', null,
    '[]'::jsonb, null,
    'fee-input', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Olivia","avatar":"🏦","emotion":"helpful","goal":"provide information","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'fee-input', 4, 'input',
    null, 'Sure! What currency do you want to exchange, and do you want to know the fee?', 'Напишіть англійською, що ви хочете дізнатися, скільки коштує комісія.',
    '[]'::jsonb, '{"acceptedAnswers":["Could you tell me how much the fee is?"]}'::jsonb,
    'fee-response-dialogue', '{}'::jsonb,
    '{"mode":"case_insensitive","points":1,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Чудово! Конструкція \"Could you tell me...\" робить ваше запитання ввічливим і м''яким, що дуже цінують у службі підтримки.","feedbackIncorrect":"Природніше англійською: Could you tell me how much the fee is?\n\nЧому саме так: \"Could you tell me...?\" чудово підходить для ввічливих запитів про інформацію.\n\nЗапам''ятайте: \"Could you tell me...?\" — універсальний ввічливий початок запитання."}'::jsonb, '{"role":"learner","avatar":"🧑‍💼","emotion":"neutral","goal":"ask about fees","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'fee-response-dialogue', 5, 'dialogue',
    'Olivia', 'The fee for exchanging cash is 2%. Would you like to proceed?', null,
    '[]'::jsonb, null,
    'cash-confirmation-dialogue', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Olivia","avatar":"🏦","emotion":"informative","goal":"inform about the fee","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'cash-confirmation-dialogue', 6, 'dialogue',
    'Olivia', 'How much cash would you like to exchange?', null,
    '[]'::jsonb, null,
    'exchange-amount-input', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Olivia","avatar":"🏦","emotion":"inquisitive","goal":"get details","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'exchange-amount-input', 7, 'input',
    null, 'How much cash would you like to exchange?', 'Напишіть англійською, скільки ви хочете обміняти.',
    '[]'::jsonb, '{"acceptedAnswers":["I''d like to exchange 100 euros, please."]}'::jsonb,
    'identification-dialogue', '{}'::jsonb,
    '{"mode":"case_insensitive","points":1,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Чудово! Ви застосували конструкцію \"I''d like to...\" правильно. Це формулювання звучить дуже ввічливо.","feedbackIncorrect":"Природніше англійською: I''d like to exchange 100 euros, please.\n\nЧому саме так: \"I''d like to...\" — це ввічливе прохання, яке використовується в обслуговуванні.\n\nЗапам''ятайте: \"I''d like to...\" — універсальний спосіб зробити ввічливе прохання."}'::jsonb, '{"role":"learner","avatar":"🧑‍💼","emotion":"neutral","goal":"confirm exchange amount","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'identification-dialogue', 8, 'dialogue',
    'Olivia', 'I need your identification for the transaction. Do you have it with you?', null,
    '[]'::jsonb, null,
    'id-provide-input', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Olivia","avatar":"🏦","emotion":"professional","goal":"request ID","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'id-provide-input', 9, 'input',
    null, 'I need your identification for the transaction. Do you have it with you?', 'Напишіть англійською, що ви передаєте свої документи.',
    '[]'::jsonb, '{"acceptedAnswers":["Yes, here is my identification."]}'::jsonb,
    'receipt-confirmation-dialogue', '{}'::jsonb,
    '{"mode":"case_insensitive","points":1,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Чудово! Фраза \"Here is...\" дуже природно звучить при передачі документів.","feedbackIncorrect":"Природніше англійською: Yes, here is my identification.\n\nЧому саме так: \"Here is...\" використовується, коли ви передаєте документи або елементи іншій людині.\n\nЗапам''ятайте: \"Here is...\" — коли передаєте документ або предмет."}'::jsonb, '{"role":"learner","avatar":"🧑‍💼","emotion":"neutral","goal":"provide ID","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'receipt-confirmation-dialogue', 10, 'dialogue',
    'Olivia', 'Once I process the transaction, I will give you a receipt. Is that okay?', null,
    '[]'::jsonb, null,
    'receipt-agreement-input', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Olivia","avatar":"🏦","emotion":"clear","goal":"confirm receipt","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'receipt-agreement-input', 11, 'input',
    null, 'Once I process the transaction, I will give you a receipt. Is that okay?', 'Напишіть англійською, що ви погоджуєтеся з отриманням чека.',
    '[]'::jsonb, '{"acceptedAnswers":["Yes, that’s fine, thank you."]}'::jsonb,
    'summary', '{}'::jsonb,
    '{"mode":"case_insensitive","points":1,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Чудово! Ваша відповідь \"that’s fine\" звучить природно у цій ситуації.","feedbackIncorrect":"Природніше англійською: Yes, that’s fine, thank you.\n\nЧому саме так: \"that’s fine\" — простий і ввічливий спосіб погодитися з чимось.\n\nЗапам''ятайте: \"that’s fine\" — природна фраза для погодження."}'::jsonb, '{"role":"learner","avatar":"🧑‍💼","emotion":"neutral","goal":"confirm receipt","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'summary', 12, 'completion',
    null, 'You have successfully completed your transaction at the bank!', null,
    '[]'::jsonb, null,
    null, '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"learner","avatar":"🧑‍💼","emotion":"happy","goal":"finish transaction","learnedWords":[]}'::jsonb
  );
end $$;
