-- Generated by TalkHero Quest Authoring System v1

-- Generated quest: At the Bank
do $$
declare
  campaign_uuid uuid;
  episode_uuid uuid;
  quest_uuid uuid;
  act_uuid uuid;
begin
  select id into campaign_uuid from public.quest_campaigns
  where slug = 'english-basics' and status = 'published';
  if campaign_uuid is null then raise exception 'Campaign not found: english-basics'; end if;

  select id into episode_uuid from public.quest_episodes
  where campaign_id = campaign_uuid and slug = 'first-contact' and status = 'published';
  if episode_uuid is null then raise exception 'Episode not found: first-contact'; end if;

  select id into quest_uuid from public.quests
  where episode_id = episode_uuid and slug = 'bank';

  if quest_uuid is null then
    insert into public.quests (
      episode_id, slug, title, description, quest_type, cefr_level,
      order_index, estimated_minutes, xp_reward, coin_reward, status, config, metadata
    ) values (
      episode_uuid, 'bank', 'At the Bank', 'Learn to exchange money politely and understand key conditions at the bank.',
      'conversation', 'A2', 6, 12,
      75, 25, 'published', '{"version":1,"sceneCount":15,"staticTest":true,"generated":true}'::jsonb, '{"templateCategory":"static","staticTest":true,"staticQuest":true,"generatedBy":"TalkHero Quest Authoring System v1","adventure":"london-first-day","location":"London"}'::jsonb
    ) returning id into quest_uuid;
  else
    update public.quests set
      title='At the Bank', description='Learn to exchange money politely and understand key conditions at the bank.', quest_type='conversation',
      cefr_level='A2', order_index=6,
      estimated_minutes=12, xp_reward=75, coin_reward=25,
      status='published', config='{"version":1,"sceneCount":15,"staticTest":true,"generated":true}'::jsonb,
      metadata=coalesce(metadata,'{}'::jsonb)||'{"templateCategory":"static","staticTest":true,"staticQuest":true,"generatedBy":"TalkHero Quest Authoring System v1","adventure":"london-first-day","location":"London"}'::jsonb, updated_at=now()
    where id=quest_uuid;
  end if;

select id
into act_uuid
from public.quest_acts
where quest_id = quest_uuid
order by order_index
limit 1;

  if act_uuid is null then
    insert into public.quest_acts (
      quest_id, act_code, title, description, order_index, status, checkpoint, metadata
    ) values (
      quest_uuid, 'bank-services', 'Bank Services', 'Engage with bank services for currency exchange.',
      0, 'published', false, '{"generated":true}'::jsonb
    ) returning id into act_uuid;
else
  update public.quest_acts
  set
    act_code = 'bank-services',
    title = 'Bank Services',
    description = 'Engage with bank services for currency exchange.',
    order_index = 0,
    status = 'published',
    updated_at = now()
  where id = act_uuid;
end if;

  delete from public.quest_scenes where quest_id=quest_uuid;

  insert into public.quest_scenes (
    quest_id, act_id, scene_code, order_index, scene_type, speaker,
    content, prompt, options, expected_answer, next_scene_code,
    branching, evaluation_config, metadata
  ) values
  (
    quest_uuid, act_uuid, 'narration-1', 0, 'narration',
    null, 'You walk into a London bank, looking to exchange some money.', null,
    '[]'::jsonb, null,
    'dialogue-1', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"","avatar":"СЂСџвЂ™В¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'dialogue-1', 1, 'dialogue',
    'Olivia', 'Hello! How can I assist you today?', null,
    '[]'::jsonb, null,
    'input-1', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"","avatar":"СЂСџвЂ™В¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'input-1', 2, 'input',
    null, 'Hello! How can I assist you today?', 'РќР°РїРёС€С–С‚СЊ Р°РЅРіР»С–Р№СЃСЊРєРѕСЋ, С‰Рѕ РІРё С…РѕС‡РµС‚Рµ РѕР±РјС–РЅСЏС‚Рё РіСЂРѕС€С–.',
    '[]'::jsonb, '{"acceptedAnswers":["I would like to exchange some money, please.","I''d like to exchange some money."]}'::jsonb,
    'dialogue-2', '{}'::jsonb,
    '{"mode":"case_insensitive","points":1,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Р§СѓРґРѕРІРѕ! РљРѕРЅСЃС‚СЂСѓРєС†С–СЏ вЂњI''d like to...вЂќ Р·РІСѓС‡РёС‚СЊ РІРІС–С‡Р»РёРІРѕ Р№ РїСЂРёСЂРѕРґРЅРѕ РґР»СЏ РїРѕРґС–Р±РЅРёС… СЃРёС‚СѓР°С†С–Р№.","feedbackIncorrect":"РџСЂРёСЂРѕРґРЅС–С€Рµ Р°РЅРіР»С–Р№СЃСЊРєРѕСЋ: I''d like to exchange some money, please.\n\nР§РѕРјСѓ СЃР°РјРµ С‚Р°Рє: вЂњI''d like to...вЂќ С” РІРІС–С‡Р»РёРІРёРј СЃРїРѕСЃРѕР±РѕРј РІРёСЃР»РѕРІРёС‚Рё Р±Р°Р¶Р°РЅРЅСЏ, С‰РѕР± РІР°Рј РґРѕРїРѕРјРѕРіР»Рё.\n\nР—Р°РїР°Рј''СЏС‚Р°Р№С‚Рµ: вЂњI''d like to...вЂќ вЂ” СѓРЅС–РІРµСЂСЃР°Р»СЊРЅРёР№ РїРѕС‡Р°С‚РѕРє РІРІС–С‡Р»РёРІРѕРіРѕ РїСЂРѕС…Р°РЅРЅСЏ."}'::jsonb, '{"role":"","avatar":"СЂСџвЂ™В¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'dialogue-2', 3, 'dialogue',
    'Olivia', 'Sure! What currency would you like to exchange?', null,
    '[]'::jsonb, null,
    'input-2', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"","avatar":"СЂСџвЂ™В¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'input-2', 4, 'input',
    null, 'Sure! What currency would you like to exchange?', 'РќР°РїРёС€С–С‚СЊ Р°РЅРіР»С–Р№СЃСЊРєРѕСЋ, С‰Рѕ РІРё С…РѕС‡РµС‚Рµ РѕР±РјС–РЅСЏС‚Рё С”РІСЂРѕ.',
    '[]'::jsonb, '{"acceptedAnswers":["I would like to change my euros.","I''d like to exchange my euros."]}'::jsonb,
    'dialogue-3', '{}'::jsonb,
    '{"mode":"case_insensitive","points":1,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Р§СѓРґРѕРІРѕ! Р’Рё РїСЂР°РІРёР»СЊРЅРѕ РІРёРєРѕСЂРёСЃС‚РѕРІСѓС”С‚Рµ РєРѕРЅСЃС‚СЂСѓРєС†С–СЋ вЂњI''d like to...вЂќ РґР»СЏ РІРІС–С‡Р»РёРІРѕРіРѕ Р·Р°РїРёС‚Сѓ.","feedbackIncorrect":"РџСЂРёСЂРѕРґРЅС–С€Рµ Р°РЅРіР»С–Р№СЃСЊРєРѕСЋ: I''d like to exchange my euros.\n\nР§РѕРјСѓ СЃР°РјРµ С‚Р°Рє: вЂњExchangeвЂќ С” РєСЂР°С‰РёРј СЃР»РѕРІРѕРј РґР»СЏ РІСЃС–С… РѕРїРµСЂР°С†С–Р№ Р· РІР°Р»СЋС‚РѕСЋ РІ Р±Р°РЅРєСѓ.\n\nР—Р°РїР°Рј''СЏС‚Р°Р№С‚Рµ: вЂњI''d like to exchange...вЂќ вЂ” РІРІС–С‡Р»РёРІРёР№ РїРѕС‡Р°С‚РѕРє Р·Р°РїРёС‚Сѓ РЅР° РѕР±РјС–РЅ."}'::jsonb, '{"role":"","avatar":"СЂСџвЂ™В¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'dialogue-3', 5, 'dialogue',
    'Olivia', 'Great! Do you have an identification?', null,
    '[]'::jsonb, null,
    'input-3', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"","avatar":"СЂСџвЂ™В¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'input-3', 6, 'input',
    null, 'Great! Do you have an identification?', 'РќР°РїРёС€С–С‚СЊ Р°РЅРіР»С–Р№СЃСЊРєРѕСЋ, С‰Рѕ РІРё РїРµСЂРµРґР°С”С‚Рµ СЃРІРѕС” РїРѕСЃРІС–РґС‡РµРЅРЅСЏ.',
    '[]'::jsonb, '{"acceptedAnswers":["Yes, here is my identification.","Here is my ID."]}'::jsonb,
    'dialogue-4', '{}'::jsonb,
    '{"mode":"case_insensitive","points":1,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Р§СѓРґРѕРІРѕ! вЂњHere is my identification.вЂќ Р·РІСѓС‡РёС‚СЊ РІРІС–С‡Р»РёРІРѕ Р№ СЏСЃРЅРѕ РІ С‚Р°РєРёС… СЃРёС‚СѓР°С†С–СЏС….","feedbackIncorrect":"РџСЂРёСЂРѕРґРЅС–С€Рµ Р°РЅРіР»С–Р№СЃСЊРєРѕСЋ: Here is my ID.\n\nР§РѕРјСѓ СЃР°РјРµ С‚Р°Рє: вЂњIDвЂќ С†Рµ Р·РІРёС‡РЅР° Р°Р±СЂРµРІС–Р°С‚СѓСЂР° РґР»СЏ РґРѕРєСѓРјРµРЅС‚Р°, СЏРєРёР№ РїС–РґС‚РІРµСЂРґР¶СѓС” РѕСЃРѕР±Сѓ, РїСЂРѕСЃС‚С–С€Р° РІ РІРёРєРѕСЂРёСЃС‚Р°РЅРЅС–.\n\nР—Р°РїР°Рј''СЏС‚Р°Р№С‚Рµ: вЂњHere is my ID.вЂќ вЂ” РїСЂРёСЂРѕРґРЅРёР№ СЃРїРѕСЃС–Р± РїРµСЂРµРґР°С‚Рё РґРѕРєСѓРјРµРЅС‚."}'::jsonb, '{"role":"","avatar":"СЂСџвЂ™В¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'dialogue-4', 7, 'dialogue',
    'Olivia', 'Thank you! Now, let me check the exchange rate and fees for you.', null,
    '[]'::jsonb, null,
    'narration-2', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"","avatar":"СЂСџвЂ™В¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'narration-2', 8, 'narration',
    null, 'While you wait, you think about the fees for exchanging money.', null,
    '[]'::jsonb, null,
    'dialogue-5', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"","avatar":"СЂСџвЂ™В¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'dialogue-5', 9, 'dialogue',
    'Olivia', 'The exchange rate today is 1 euro to 1.15 pounds, and the fee is 2% of the amount.', null,
    '[]'::jsonb, null,
    'input-4', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"","avatar":"СЂСџвЂ™В¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'input-4', 10, 'input',
    null, 'The exchange rate today is 1 euro to 1.15 pounds, and the fee is 2% of the amount.', 'Р—Р°РїРёС‚Р°Р№С‚Рµ РїСЂРѕ СЂРѕР·РјС–СЂ РєРѕРјС–СЃС–С—.',
    '[]'::jsonb, '{"acceptedAnswers":["How much will the fee be?","How much is the fee?"]}'::jsonb,
    'dialogue-6', '{}'::jsonb,
    '{"mode":"case_insensitive","points":1,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Р§СѓРґРѕРІРѕ! РџРёС‚Р°РЅРЅСЏ вЂњHow much will the fee be?вЂќ С” РїСЂРёСЂРѕРґРЅРёРј С– С†С–Р»РµСЃРїСЂСЏРјРѕРІР°РЅРёРј.","feedbackIncorrect":"РџСЂРёСЂРѕРґРЅС–С€Рµ Р°РЅРіР»С–Р№СЃСЊРєРѕСЋ: How much will the fee be?\n\nР§РѕРјСѓ СЃР°РјРµ С‚Р°Рє: Р¦Рµ РїСЂСЏРјР° С„РѕСЂРјР° Р·Р°РїРёС‚Р°РЅРЅСЏ РґРѕРїРѕРјР°РіР°С” РѕС‚СЂРёРјР°С‚Рё С‚РѕС‡РЅСѓ С–РЅС„РѕСЂРјР°С†С–СЋ РїСЂРѕ РІРёС‚СЂР°С‚Рё.\n\nР—Р°РїР°Рј''СЏС‚Р°Р№С‚Рµ: вЂњHow much is the fee?вЂќ вЂ” РїСЂРѕСЃС‚Рµ РїРёС‚Р°РЅРЅСЏ РґР»СЏ СѓС‚РѕС‡РЅРµРЅРЅСЏ РІРёС‚СЂР°С‚."}'::jsonb, '{"role":"","avatar":"СЂСџвЂ™В¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'dialogue-6', 11, 'dialogue',
    'Olivia', 'The fee will be 2 pounds for 100 euros.', null,
    '[]'::jsonb, null,
    'input-5', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"","avatar":"СЂСџвЂ™В¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'input-5', 12, 'input',
    null, 'The fee will be 2 pounds for 100 euros.', 'РќР°РїРёС€С–С‚СЊ Р°РЅРіР»С–Р№СЃСЊРєРѕСЋ, С‰Рѕ РІРё С…РѕС‡РµС‚Рµ РїС–РґС‚РІРµСЂРґРёС‚Рё С‚СЂР°РЅР·Р°РєС†С–СЋ.',
    '[]'::jsonb, '{"acceptedAnswers":["I would like to confirm the transaction.","I''d like to confirm the transaction."]}'::jsonb,
    'dialogue-7', '{}'::jsonb,
    '{"mode":"case_insensitive","points":1,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Р§СѓРґРѕРІРѕ! вЂњI''d like to confirm the transaction.вЂќ вЂ” РІРІС–С‡Р»РёРІРёР№ С– С‡С–С‚РєРёР№ СЃРїРѕСЃС–Р± РїС–РґС‚РІРµСЂРґРёС‚Рё РІР°С€Сѓ СѓРіРѕРґСѓ.","feedbackIncorrect":"РџСЂРёСЂРѕРґРЅС–С€Рµ Р°РЅРіР»С–Р№СЃСЊРєРѕСЋ: I''d like to confirm the transaction.\n\nР§РѕРјСѓ СЃР°РјРµ С‚Р°Рє: вЂњI''d like to...вЂќ Р·Р°Р±РµР·РїРµС‡СѓС” РІРІС–С‡Р»РёРІРµ Р·РІСѓС‡Р°РЅРЅСЏ РІР°С€РѕРіРѕ РїС–РґС‚РІРµСЂРґР¶РµРЅРЅСЏ, РїС–РґРєСЂРµСЃР»СЋСЋС‡Рё РІР°С€Сѓ СЃРµСЂР№РѕР·РЅС–СЃС‚СЊ.\n\nР—Р°РїР°Рј''СЏС‚Р°Р№С‚Рµ: вЂњI''d like to confirm...вЂќ вЂ” РІРІС–С‡Р»РёРІРёР№ СЃРїРѕСЃС–Р± РІРёСЃР»РѕРІРёС‚Рё РІР°С€Сѓ Р·РіРѕРґСѓ."}'::jsonb, '{"role":"","avatar":"СЂСџвЂ™В¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'dialogue-7', 13, 'dialogue',
    'Olivia', 'Thank you! Here is your receipt. Have a great day!', null,
    '[]'::jsonb, null,
    'summary', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"","avatar":"СЂСџвЂ™В¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'summary', 14, 'completion',
    null, 'You have successfully completed the transaction and exchanged your euros. You feel pleased with your experience at the bank.', null,
    '[]'::jsonb, null,
    null, '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"","avatar":"СЂСџвЂ™В¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  );
end $$;
