-- Generated by TalkHero Quest Authoring System v1

-- Generated quest: At the Bank
do $$
declare
  campaign_uuid uuid;
  episode_uuid uuid;
  quest_uuid uuid;
  act_uuid uuid;
begin
  select id into campaign_uuid from public.quest_campaigns
  where slug = 'english-basics' and status = 'published';
  if campaign_uuid is null then raise exception 'Campaign not found: english-basics'; end if;

  select id into episode_uuid from public.quest_episodes
  where campaign_id = campaign_uuid and slug = 'first-contact' and status = 'published';
  if episode_uuid is null then raise exception 'Episode not found: first-contact'; end if;

  select id into quest_uuid from public.quests
  where episode_id = episode_uuid and slug = 'bank';

  if quest_uuid is null then
    insert into public.quests (
      episode_id, slug, title, description, quest_type, cefr_level,
      order_index, estimated_minutes, xp_reward, coin_reward, status, config, metadata
    ) values (
      episode_uuid, 'bank', 'At the Bank', 'You visit a London bank to exchange money and ask about fees with Olivia, the bank clerk.',
      'conversation', 'A2', 6, 12,
      75, 25, 'published', '{"version":1,"sceneCount":14,"staticTest":true,"generated":true}'::jsonb, '{"templateCategory":"static","staticTest":true,"staticQuest":true,"generatedBy":"TalkHero Quest Authoring System v1","adventure":"london-first-day","location":"London"}'::jsonb
    ) returning id into quest_uuid;
  else
    update public.quests set
      title='At the Bank', description='You visit a London bank to exchange money and ask about fees with Olivia, the bank clerk.', quest_type='conversation',
      cefr_level='A2', order_index=6,
      estimated_minutes=12, xp_reward=75, coin_reward=25,
      status='published', config='{"version":1,"sceneCount":14,"staticTest":true,"generated":true}'::jsonb,
      metadata=coalesce(metadata,'{}'::jsonb)||'{"templateCategory":"static","staticTest":true,"staticQuest":true,"generatedBy":"TalkHero Quest Authoring System v1","adventure":"london-first-day","location":"London"}'::jsonb, updated_at=now()
    where id=quest_uuid;
  end if;

  select id into act_uuid from public.quest_acts
  where quest_id=quest_uuid and act_code='currency-exchange';

  if act_uuid is null then
    insert into public.quest_acts (
      quest_id, act_code, title, description, order_index, status, checkpoint, metadata
    ) values (
      quest_uuid, 'currency-exchange', 'Currency Exchange', 'Learn to conduct a currency exchange transaction.',
      0, 'published', false, '{"generated":true}'::jsonb
    ) returning id into act_uuid;
  else
    update public.quest_acts set
      title='Currency Exchange', description='Learn to conduct a currency exchange transaction.',
      status='published', updated_at=now()
    where id=act_uuid;
  end if;

  delete from public.quest_scenes where quest_id=quest_uuid;

  insert into public.quest_scenes (
    quest_id, act_id, scene_code, order_index, scene_type, speaker,
    content, prompt, options, expected_answer, next_scene_code,
    branching, evaluation_config, metadata
  ) values
  (
    quest_uuid, act_uuid, 'narration-1', 0, 'narration',
    null, 'You enter a bank in London. It is busy, but you see a polite woman at the counter.', null,
    '[]'::jsonb, null,
    'dialogue-1', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"learner","avatar":"💬","emotion":"neutral","goal":"exchange money","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'dialogue-1', 1, 'dialogue',
    'Olivia', 'Hello! How can I help you today?', null,
    '[]'::jsonb, null,
    'choice-1', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"bank clerk","avatar":"🏦","emotion":"friendly","goal":"assist the customer","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'choice-1', 2, 'choice',
    null, 'How do you respond?', null,
    '[{"id":"1","text":"I’d like to exchange some cash.","value":"I’d like to exchange some cash."},{"id":"2","text":"I want to go to the bank.","value":"I want to go to the bank."},{"id":"3","text":"Can I help you?","value":"Can I help you?"}]'::jsonb, '{"optionId":"1"}'::jsonb,
    'dialogue-2', '{}'::jsonb,
    '{"mode":"exact","points":1,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Правильно!","feedbackIncorrect":"Спробуйте ще раз."}'::jsonb, '{"role":"learner","avatar":"💬","emotion":"neutral","goal":"initiate conversation","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'dialogue-2', 3, 'dialogue',
    'Olivia', 'Sure! What currency do you want to exchange?', null,
    '[]'::jsonb, null,
    'choice-2', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"bank clerk","avatar":"🏦","emotion":"helpful","goal":"assist the customer","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'choice-2', 4, 'choice',
    null, 'You say:', null,
    '[{"id":"1","text":"I want to exchange dollars.","value":"I want to exchange dollars."},{"id":"2","text":"I need my money.","value":"I need my money."},{"id":"3","text":"How can I go there?","value":"How can I go there?"}]'::jsonb, '{"optionId":"1"}'::jsonb,
    'dialogue-3', '{}'::jsonb,
    '{"mode":"exact","points":1,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Правильно!","feedbackIncorrect":"Спробуйте ще раз."}'::jsonb, '{"role":"learner","avatar":"💬","emotion":"neutral","goal":"inform about currency","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'dialogue-3', 5, 'dialogue',
    'Olivia', 'Great! The exchange rate today is 1 dollar for 0.75 pounds. Do you want to know about the fees?', null,
    '[]'::jsonb, null,
    'choice-3', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"bank clerk","avatar":"🏦","emotion":"informative","goal":"provide information","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'choice-3', 6, 'choice',
    null, 'What do you ask?', null,
    '[{"id":"1","text":"Could you tell me about the fees?","value":"Could you tell me about the fees?"},{"id":"2","text":"What is a fee?","value":"What is a fee?"},{"id":"3","text":"Do I need help?","value":"Do I need help?"}]'::jsonb, '{"optionId":"1"}'::jsonb,
    'dialogue-4', '{}'::jsonb,
    '{"mode":"exact","points":1,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Правильно!","feedbackIncorrect":"Спробуйте ще раз."}'::jsonb, '{"role":"learner","avatar":"💬","emotion":"neutral","goal":"ask about fees","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'dialogue-4', 7, 'dialogue',
    'Olivia', 'Yes, we charge a fee of 5 pounds for exchanges under 100 pounds.', null,
    '[]'::jsonb, null,
    'dialogue-5', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"bank clerk","avatar":"🏦","emotion":"clear","goal":"answer the question","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'dialogue-5', 8, 'dialogue',
    'Olivia', 'Do you have identification with you?', null,
    '[]'::jsonb, null,
    'choice-4', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"bank clerk","avatar":"🏦","emotion":"inquisitive","goal":"request identification","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'choice-4', 9, 'choice',
    null, 'You respond:', null,
    '[{"id":"1","text":"Yes, I have my passport.","value":"Yes, I have my passport."},{"id":"2","text":"No, I don’t need it.","value":"No, I don’t need it."},{"id":"3","text":"What is identification?","value":"What is identification?"}]'::jsonb, '{"optionId":"1"}'::jsonb,
    'dialogue-6', '{}'::jsonb,
    '{"mode":"exact","points":1,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Правильно!","feedbackIncorrect":"Спробуйте ще раз."}'::jsonb, '{"role":"learner","avatar":"💬","emotion":"neutral","goal":"confirm with identification","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'dialogue-6', 10, 'dialogue',
    'Olivia', 'Perfect! Please fill out this form and I will assist you with the transaction.', null,
    '[]'::jsonb, null,
    'input-1', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"bank clerk","avatar":"🏦","emotion":"supportive","goal":"assist the learner","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'input-1', 11, 'input',
    null, 'Fill out your name and amount you want to exchange:', 'What is your name and the amount?',
    '[]'::jsonb, '{"acceptedAnswers":["John Doe 100","Jane Smith 50","Alex 150"]}'::jsonb,
    'dialogue-7', '{}'::jsonb,
    '{"mode":"case_insensitive","points":1,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Thank you!","feedbackIncorrect":"Please provide your name and the amount."}'::jsonb, '{"role":"learner","avatar":"💬","emotion":"neutral","goal":"provide information","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'dialogue-7', 12, 'dialogue',
    'Olivia', 'Thank you! Your transaction is complete. Here is your receipt.', null,
    '[]'::jsonb, null,
    'summary', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"bank clerk","avatar":"🏦","emotion":"satisfied","goal":"complete the transaction","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'summary', 13, 'completion',
    null, 'You''ve successfully completed your currency exchange and learned key phrases for banking. Good job!', null,
    '[]'::jsonb, null,
    null, '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"learner","avatar":"💬","emotion":"happy","goal":"reflect on learning","learnedWords":[]}'::jsonb
  );
end $$;
