-- Generated by TalkHero Quest Authoring System v1

-- Generated quest: At the Pharmacy
do $$
declare
  campaign_uuid uuid;
  episode_uuid uuid;
  quest_uuid uuid;
  act_uuid uuid;
begin
  select id into campaign_uuid from public.quest_campaigns
  where slug = 'english-basics' and status = 'published';
  if campaign_uuid is null then raise exception 'Campaign not found: english-basics'; end if;

  select id into episode_uuid from public.quest_episodes
  where campaign_id = campaign_uuid and slug = 'first-contact' and status = 'published';
  if episode_uuid is null then raise exception 'Episode not found: first-contact'; end if;

  select id into quest_uuid from public.quests
  where episode_id = episode_uuid and slug = 'pharmacy';

  if quest_uuid is null then
    insert into public.quests (
      episode_id, slug, title, description, quest_type, cefr_level,
      order_index, estimated_minutes, xp_reward, coin_reward, status, config, metadata
    ) values (
      episode_uuid, 'pharmacy', 'At the Pharmacy', 'Describe symptoms, choose medicine, understand dosage instructions and pay.',
      'conversation', 'A1', 7, 11,
      75, 25, 'published', '{"version":1,"sceneCount":16,"staticTest":true,"generated":true}'::jsonb, '{"templateCategory":"health","staticTest":true,"staticQuest":true,"generatedBy":"TalkHero Quest Authoring System v1","adventure":"london-first-day","location":"pharmacy"}'::jsonb
    ) returning id into quest_uuid;
  else
    update public.quests set
      title='At the Pharmacy', description='Describe symptoms, choose medicine, understand dosage instructions and pay.', quest_type='conversation',
      cefr_level='A1', order_index=7,
      estimated_minutes=11, xp_reward=75, coin_reward=25,
      status='published', config='{"version":1,"sceneCount":16,"staticTest":true,"generated":true}'::jsonb,
      metadata=coalesce(metadata,'{}'::jsonb)||'{"templateCategory":"health","staticTest":true,"staticQuest":true,"generatedBy":"TalkHero Quest Authoring System v1","adventure":"london-first-day","location":"pharmacy"}'::jsonb, updated_at=now()
    where id=quest_uuid;
  end if;

  select id into act_uuid from public.quest_acts
  where quest_id=quest_uuid and act_code='main';

  if act_uuid is null then
    insert into public.quest_acts (
      quest_id, act_code, title, description, order_index, status, checkpoint, metadata
    ) values (
      quest_uuid, 'main', 'At the pharmacy', 'Ask a pharmacist for suitable medicine.',
      0, 'published', false, '{"generated":true}'::jsonb
    ) returning id into act_uuid;
  else
    update public.quest_acts set
      title='At the pharmacy', description='Ask a pharmacist for suitable medicine.',
      status='published', updated_at=now()
    where id=act_uuid;
  end if;

  delete from public.quest_scenes where quest_id=quest_uuid;

  insert into public.quest_scenes (
    quest_id, act_id, scene_code, order_index, scene_type, speaker,
    content, prompt, options, expected_answer, next_scene_code,
    branching, evaluation_config, metadata
  ) values
  (
    quest_uuid, act_uuid, 'intro', 0, 'narration',
    'Емма', 'Ви зайшли до аптеки. Потрібно описати симптоми, обрати ліки, зрозуміти інструкцію та оплатити покупку.', null,
    '[]'::jsonb, null,
    'greeting', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Ваш наставник","avatar":"🙂","emotion":"encouraging","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'greeting', 1, 'dialogue',
    'Emma', 'Good afternoon. How can I help you?', null,
    '[]'::jsonb, null,
    'opening-choice', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Pharmacist","avatar":"💊","emotion":"friendly","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'opening-choice', 2, 'choice',
    'Emma', 'Choose the most suitable response.', 'У вас болить голова.',
    '[{"id":"headache","text":"I have a headache.","value":"headache"},{"id":"ticket","text":"I need a train ticket.","value":"ticket"},{"id":"reservation","text":"I have a reservation.","value":"reservation"}]'::jsonb, '{"optionId":"headache"}'::jsonb,
    'symptom-question', '{}'::jsonb,
    '{"mode":"exact","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Правильно! Ви чітко назвали симптом.","feedbackIncorrect":"Оберіть фразу I have a headache."}'::jsonb, '{"role":"Pharmacist","avatar":"💊","emotion":"neutral","goal":"describe symptom","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'symptom-question', 3, 'dialogue',
    'Emma', 'How long have you had it?', null,
    '[]'::jsonb, null,
    'duration-input', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Pharmacist","avatar":"💊","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'duration-input', 4, 'input',
    'Emma', 'How long have you had the headache?', 'Напишіть, що головний біль триває зранку.',
    '[]'::jsonb, '{"acceptedAnswers":["Since this morning","I have had it since this morning","I''ve had it since this morning"]}'::jsonb,
    'cough-translate', '{}'::jsonb,
    '{"mode":"case_insensitive","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Добре! Ви правильно назвали тривалість.","feedbackIncorrect":"Спробуйте: Since this morning."}'::jsonb, '{"role":"Pharmacist","avatar":"💊","emotion":"neutral","goal":"state duration","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'cough-translate', 5, 'translate',
    'Емма', 'У мене також є кашель.', 'Перекладіть англійською.',
    '[]'::jsonb, '{"acceptedAnswers":["I also have a cough","I have a cough too","I also have cough"]}'::jsonb,
    'prescription-question', '{}'::jsonb,
    '{"mode":"case_insensitive","points":15,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Чудово! Ви додали ще один симптом.","feedbackIncorrect":"Спробуйте: I also have a cough."}'::jsonb, '{"role":"Ваш наставник","avatar":"🙂","emotion":"neutral","goal":"describe another symptom","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'prescription-question', 6, 'dialogue',
    'Emma', 'Are you taking any other medicine?', null,
    '[]'::jsonb, null,
    'medicine-choice', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Pharmacist","avatar":"💊","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'medicine-choice', 7, 'choice',
    'Emma', 'Choose the safest simple answer.', 'Ви зараз не приймаєте інших ліків.',
    '[{"id":"none","text":"No, I am not taking any other medicine.","value":"none"},{"id":"platform","text":"The train leaves from platform five.","value":"platform"},{"id":"dessert","text":"I would like the dessert menu.","value":"dessert"}]'::jsonb, '{"optionId":"none"}'::jsonb,
    'recommendation', '{}'::jsonb,
    '{"mode":"exact","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Правильно! Це чітка відповідь фармацевту.","feedbackIncorrect":"Оберіть відповідь про інші ліки."}'::jsonb, '{"role":"Pharmacist","avatar":"💊","emotion":"neutral","goal":"answer medicine question","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'recommendation', 8, 'dialogue',
    'Emma', 'I recommend these painkillers. You do not need a prescription.', null,
    '[]'::jsonb, null,
    'tablets-input', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Pharmacist","avatar":"💊","emotion":"helpful","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'tablets-input', 9, 'input',
    'Emma', 'Would you like these tablets?', 'Напишіть, що ви візьмете ці таблетки.',
    '[]'::jsonb, '{"acceptedAnswers":["I will take these tablets","I''ll take these tablets","I would like these tablets","I''d like these tablets"]}'::jsonb,
    'instructions', '{}'::jsonb,
    '{"mode":"case_insensitive","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Добре! Ви підтвердили вибір ліків.","feedbackIncorrect":"Спробуйте: I''ll take these tablets."}'::jsonb, '{"role":"Pharmacist","avatar":"💊","emotion":"neutral","goal":"accept medicine","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'instructions', 10, 'dialogue',
    'Emma', 'Take one tablet twice a day after meals.', null,
    '[]'::jsonb, null,
    'frequency-choice', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Pharmacist","avatar":"💊","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'frequency-choice', 11, 'choice',
    'Emma', 'How often should you take the medicine?', 'Оберіть правильну частоту.',
    '[{"id":"twice","text":"Twice a day.","value":"twice"},{"id":"once-week","text":"Once a week.","value":"once-week"},{"id":"three-hours","text":"Every three hours.","value":"three-hours"}]'::jsonb, '{"optionId":"twice"}'::jsonb,
    'instruction-translate', '{}'::jsonb,
    '{"mode":"exact","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Так, ліки потрібно приймати двічі на день.","feedbackIncorrect":"Оберіть Twice a day."}'::jsonb, '{"role":"Pharmacist","avatar":"💊","emotion":"neutral","goal":"understand dosage","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'instruction-translate', 12, 'translate',
    'Емма', 'Чи потрібно приймати їх після їжі?', 'Перекладіть англійською.',
    '[]'::jsonb, '{"acceptedAnswers":["Should I take them after meals","Should I take them after meals?","Do I need to take them after meals","Do I need to take them after meals?"]}'::jsonb,
    'payment-dialogue', '{}'::jsonb,
    '{"mode":"case_insensitive","points":15,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Відмінно! Ви уточнили важливу інструкцію.","feedbackIncorrect":"Спробуйте: Should I take them after meals?"}'::jsonb, '{"role":"Ваш наставник","avatar":"🙂","emotion":"neutral","goal":"confirm instructions","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'payment-dialogue', 13, 'dialogue',
    'Emma', 'Yes, after meals. That will be eight pounds fifty.', null,
    '[]'::jsonb, null,
    'payment-choice', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Pharmacist","avatar":"💊","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'payment-choice', 14, 'choice',
    'Emma', 'Choose a polite payment response.', 'Ви платите карткою.',
    '[{"id":"card","text":"By card, please.","value":"card"},{"id":"cashier","text":"Where is the museum?","value":"cashier"},{"id":"taxi","text":"Please take me to the station.","value":"taxi"}]'::jsonb, '{"optionId":"card"}'::jsonb,
    'summary', '{}'::jsonb,
    '{"mode":"exact","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Правильно! Ви назвали спосіб оплати.","feedbackIncorrect":"Оберіть By card, please."}'::jsonb, '{"role":"Pharmacist","avatar":"💊","emotion":"neutral","goal":"pay for medicine","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'summary', 15, 'completion',
    'Емма', 'Ви описали симптоми, обрали ліки, зрозуміли дозування та оплатили покупку.', null,
    '[]'::jsonb, null,
    null, '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Ваш наставник","avatar":"🎉","emotion":"celebrating","goal":"","learnedWords":["headache","cough","painkiller","prescription","tablet","twice a day","after meals"]}'::jsonb
  );
end $$;

-- Generated quest: At the Post Office
do $$
declare
  campaign_uuid uuid;
  episode_uuid uuid;
  quest_uuid uuid;
  act_uuid uuid;
begin
  select id into campaign_uuid from public.quest_campaigns
  where slug = 'english-basics' and status = 'published';
  if campaign_uuid is null then raise exception 'Campaign not found: english-basics'; end if;

  select id into episode_uuid from public.quest_episodes
  where campaign_id = campaign_uuid and slug = 'first-contact' and status = 'published';
  if episode_uuid is null then raise exception 'Episode not found: first-contact'; end if;

  select id into quest_uuid from public.quests
  where episode_id = episode_uuid and slug = 'post-office';

  if quest_uuid is null then
    insert into public.quests (
      episode_id, slug, title, description, quest_type, cefr_level,
      order_index, estimated_minutes, xp_reward, coin_reward, status, config, metadata
    ) values (
      episode_uuid, 'post-office', 'At the Post Office', 'Send an international parcel, choose delivery, complete a form and get tracking.',
      'conversation', 'A2', 9, 12,
      80, 27, 'published', '{"version":1,"sceneCount":16,"staticTest":true,"generated":true}'::jsonb, '{"templateCategory":"services","staticTest":true,"staticQuest":true,"generatedBy":"TalkHero Quest Authoring System v1","adventure":"london-first-day","location":"post-office"}'::jsonb
    ) returning id into quest_uuid;
  else
    update public.quests set
      title='At the Post Office', description='Send an international parcel, choose delivery, complete a form and get tracking.', quest_type='conversation',
      cefr_level='A2', order_index=9,
      estimated_minutes=12, xp_reward=80, coin_reward=27,
      status='published', config='{"version":1,"sceneCount":16,"staticTest":true,"generated":true}'::jsonb,
      metadata=coalesce(metadata,'{}'::jsonb)||'{"templateCategory":"services","staticTest":true,"staticQuest":true,"generatedBy":"TalkHero Quest Authoring System v1","adventure":"london-first-day","location":"post-office"}'::jsonb, updated_at=now()
    where id=quest_uuid;
  end if;

  select id into act_uuid from public.quest_acts
  where quest_id=quest_uuid and act_code='main';

  if act_uuid is null then
    insert into public.quest_acts (
      quest_id, act_code, title, description, order_index, status, checkpoint, metadata
    ) values (
      quest_uuid, 'main', 'Sending a parcel', 'Send a tracked parcel to another country.',
      0, 'published', false, '{"generated":true}'::jsonb
    ) returning id into act_uuid;
  else
    update public.quest_acts set
      title='Sending a parcel', description='Send a tracked parcel to another country.',
      status='published', updated_at=now()
    where id=act_uuid;
  end if;

  delete from public.quest_scenes where quest_id=quest_uuid;

  insert into public.quest_scenes (
    quest_id, act_id, scene_code, order_index, scene_type, speaker,
    content, prompt, options, expected_answer, next_scene_code,
    branching, evaluation_config, metadata
  ) values
  (
    quest_uuid, act_uuid, 'intro', 0, 'narration',
    'Емма', 'Ви прийшли на пошту, щоб відправити посилку в Україну. Потрібно назвати країну, обрати спосіб доставки, заповнити форму й оплатити.', null,
    '[]'::jsonb, null,
    'clerk-greeting', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Ваш наставник","avatar":"🙂","emotion":"encouraging","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'clerk-greeting', 1, 'dialogue',
    'Henry', 'Good morning. What would you like to send?', null,
    '[]'::jsonb, null,
    'item-choice', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Postal clerk","avatar":"📮","emotion":"friendly","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'item-choice', 2, 'choice',
    'Henry', 'Choose the correct answer.', 'Ви хочете відправити посилку.',
    '[{"id":"parcel","text":"I would like to send this parcel.","value":"parcel"},{"id":"taxi","text":"Please take me to the hotel.","value":"taxi"},{"id":"tablets","text":"I need these tablets.","value":"tablets"}]'::jsonb, '{"optionId":"parcel"}'::jsonb,
    'destination-question', '{}'::jsonb,
    '{"mode":"exact","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Правильно! Ви пояснили мету візиту.","feedbackIncorrect":"Оберіть фразу про відправлення посилки."}'::jsonb, '{"role":"Postal clerk","avatar":"📮","emotion":"neutral","goal":"send parcel","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'destination-question', 3, 'dialogue',
    'Henry', 'Which country are you sending it to?', null,
    '[]'::jsonb, null,
    'country-input', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Postal clerk","avatar":"📮","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'country-input', 4, 'input',
    'Henry', 'Where is the parcel going?', 'Напишіть, що посилка прямує до України.',
    '[]'::jsonb, '{"acceptedAnswers":["It is going to Ukraine","It''s going to Ukraine","To Ukraine"]}'::jsonb,
    'cost-translate', '{}'::jsonb,
    '{"mode":"case_insensitive","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Добре! Ви назвали країну призначення.","feedbackIncorrect":"Спробуйте: It''s going to Ukraine."}'::jsonb, '{"role":"Postal clerk","avatar":"📮","emotion":"neutral","goal":"state destination country","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'cost-translate', 5, 'translate',
    'Емма', 'Скільки коштує доставка?', 'Перекладіть англійською.',
    '[]'::jsonb, '{"acceptedAnswers":["How much is the delivery","How much is the delivery?","How much does delivery cost","How much does delivery cost?","How much is postage"]}'::jsonb,
    'options-dialogue', '{}'::jsonb,
    '{"mode":"case_insensitive","points":15,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Чудово! Ви правильно запитали про вартість.","feedbackIncorrect":"Спробуйте: How much does delivery cost?"}'::jsonb, '{"role":"Ваш наставник","avatar":"🙂","emotion":"neutral","goal":"ask postage cost","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'options-dialogue', 6, 'dialogue',
    'Henry', 'Standard delivery is twelve pounds. Express delivery is twenty-two pounds.', null,
    '[]'::jsonb, null,
    'delivery-choice', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Postal clerk","avatar":"📮","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'delivery-choice', 7, 'choice',
    'Henry', 'Which option is cheaper?', 'Оберіть дешевший спосіб доставки.',
    '[{"id":"standard","text":"Standard delivery.","value":"standard"},{"id":"express","text":"Express delivery.","value":"express"},{"id":"collection","text":"Hotel collection.","value":"collection"}]'::jsonb, '{"optionId":"standard"}'::jsonb,
    'arrival-dialogue', '{}'::jsonb,
    '{"mode":"exact","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Правильно! Standard delivery дешевша.","feedbackIncorrect":"Оберіть Standard delivery."}'::jsonb, '{"role":"Postal clerk","avatar":"📮","emotion":"neutral","goal":"choose delivery type","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'arrival-dialogue', 8, 'dialogue',
    'Henry', 'Standard delivery usually takes seven to ten working days.', null,
    '[]'::jsonb, null,
    'arrival-input', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Postal clerk","avatar":"📮","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'arrival-input', 9, 'input',
    'Henry', 'Do you have any questions?', 'Запитайте, коли посилка прибуде.',
    '[]'::jsonb, '{"acceptedAnswers":["When will the parcel arrive","When will the parcel arrive?","When should the parcel arrive","When should the parcel arrive?"]}'::jsonb,
    'form-dialogue', '{}'::jsonb,
    '{"mode":"case_insensitive","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Правильно! Ви уточнили строк доставки.","feedbackIncorrect":"Спробуйте: When will the parcel arrive?"}'::jsonb, '{"role":"Postal clerk","avatar":"📮","emotion":"neutral","goal":"ask arrival time","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'form-dialogue', 10, 'dialogue',
    'Henry', 'Please complete this customs form and write the recipient’s address clearly.', null,
    '[]'::jsonb, null,
    'contents-choice', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Postal clerk","avatar":"📮","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'contents-choice', 11, 'choice',
    'Henry', 'What information belongs on the customs form?', 'Оберіть правильну інформацію.',
    '[{"id":"contents","text":"The contents and value of the parcel.","value":"contents"},{"id":"platform","text":"The train platform.","value":"platform"},{"id":"medicine","text":"The medicine dosage.","value":"medicine"}]'::jsonb, '{"optionId":"contents"}'::jsonb,
    'tracking-translate', '{}'::jsonb,
    '{"mode":"exact","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Так, потрібно вказати вміст і вартість посилки.","feedbackIncorrect":"Оберіть інформацію про вміст і вартість."}'::jsonb, '{"role":"Postal clerk","avatar":"📮","emotion":"neutral","goal":"understand customs form","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'tracking-translate', 12, 'translate',
    'Емма', 'Чи є номер для відстеження?', 'Перекладіть англійською.',
    '[]'::jsonb, '{"acceptedAnswers":["Is there a tracking number","Is there a tracking number?","Does it have a tracking number","Does it have a tracking number?","Can I have a tracking number"]}'::jsonb,
    'payment-dialogue', '{}'::jsonb,
    '{"mode":"case_insensitive","points":15,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Відмінно! Ви запитали про відстеження.","feedbackIncorrect":"Спробуйте: Is there a tracking number?"}'::jsonb, '{"role":"Ваш наставник","avatar":"🙂","emotion":"neutral","goal":"ask tracking number","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'payment-dialogue', 13, 'dialogue',
    'Henry', 'Yes. The tracking number is on your receipt. The total is twelve pounds.', null,
    '[]'::jsonb, null,
    'payment-choice', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Postal clerk","avatar":"📮","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'payment-choice', 14, 'choice',
    'Henry', 'How would you like to pay?', 'Ви платите карткою.',
    '[{"id":"card","text":"By card, please.","value":"card"},{"id":"taxi","text":"Take a different route.","value":"taxi"},{"id":"allergy","text":"I am allergic to nuts.","value":"allergy"}]'::jsonb, '{"optionId":"card"}'::jsonb,
    'summary', '{}'::jsonb,
    '{"mode":"exact","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Правильно! Ви назвали спосіб оплати.","feedbackIncorrect":"Оберіть By card, please."}'::jsonb, '{"role":"Postal clerk","avatar":"📮","emotion":"neutral","goal":"pay postage","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'summary', 15, 'completion',
    'Емма', 'Ви відправили посилку, обрали доставку, заповнили митну форму, отримали номер відстеження й оплатили послугу.', null,
    '[]'::jsonb, null,
    null, '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Ваш наставник","avatar":"🎉","emotion":"celebrating","goal":"","learnedWords":["parcel","postage","standard delivery","express delivery","customs form","recipient","tracking number"]}'::jsonb
  );
end $$;

-- Generated quest: Taxi Ride
do $$
declare
  campaign_uuid uuid;
  episode_uuid uuid;
  quest_uuid uuid;
  act_uuid uuid;
begin
  select id into campaign_uuid from public.quest_campaigns
  where slug = 'english-basics' and status = 'published';
  if campaign_uuid is null then raise exception 'Campaign not found: english-basics'; end if;

  select id into episode_uuid from public.quest_episodes
  where campaign_id = campaign_uuid and slug = 'first-contact' and status = 'published';
  if episode_uuid is null then raise exception 'Episode not found: first-contact'; end if;

  select id into quest_uuid from public.quests
  where episode_id = episode_uuid and slug = 'taxi';

  if quest_uuid is null then
    insert into public.quests (
      episode_id, slug, title, description, quest_type, cefr_level,
      order_index, estimated_minutes, xp_reward, coin_reward, status, config, metadata
    ) values (
      episode_uuid, 'taxi', 'Taxi Ride', 'Give a destination and address, discuss the route and pay for a taxi ride.',
      'conversation', 'A1', 8, 10,
      70, 24, 'published', '{"version":1,"sceneCount":16,"staticTest":true,"generated":true}'::jsonb, '{"templateCategory":"transport","staticTest":true,"staticQuest":true,"generatedBy":"TalkHero Quest Authoring System v1","adventure":"london-first-day","location":"taxi"}'::jsonb
    ) returning id into quest_uuid;
  else
    update public.quests set
      title='Taxi Ride', description='Give a destination and address, discuss the route and pay for a taxi ride.', quest_type='conversation',
      cefr_level='A1', order_index=8,
      estimated_minutes=10, xp_reward=70, coin_reward=24,
      status='published', config='{"version":1,"sceneCount":16,"staticTest":true,"generated":true}'::jsonb,
      metadata=coalesce(metadata,'{}'::jsonb)||'{"templateCategory":"transport","staticTest":true,"staticQuest":true,"generatedBy":"TalkHero Quest Authoring System v1","adventure":"london-first-day","location":"taxi"}'::jsonb, updated_at=now()
    where id=quest_uuid;
  end if;

  select id into act_uuid from public.quest_acts
  where quest_id=quest_uuid and act_code='main';

  if act_uuid is null then
    insert into public.quest_acts (
      quest_id, act_code, title, description, order_index, status, checkpoint, metadata
    ) values (
      quest_uuid, 'main', 'A London taxi ride', 'Reach your destination and complete the fare.',
      0, 'published', false, '{"generated":true}'::jsonb
    ) returning id into act_uuid;
  else
    update public.quest_acts set
      title='A London taxi ride', description='Reach your destination and complete the fare.',
      status='published', updated_at=now()
    where id=act_uuid;
  end if;

  delete from public.quest_scenes where quest_id=quest_uuid;

  insert into public.quest_scenes (
    quest_id, act_id, scene_code, order_index, scene_type, speaker,
    content, prompt, options, expected_answer, next_scene_code,
    branching, evaluation_config, metadata
  ) values
  (
    quest_uuid, act_uuid, 'intro', 0, 'narration',
    'Емма', 'Ви сідаєте в лондонське таксі. Потрібно назвати адресу, уточнити час і ціну, а наприкінці оплатити поїздку.', null,
    '[]'::jsonb, null,
    'driver-greeting', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Ваш наставник","avatar":"🙂","emotion":"encouraging","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'driver-greeting', 1, 'dialogue',
    'George', 'Hello. Where would you like to go?', null,
    '[]'::jsonb, null,
    'destination-choice', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Taxi driver","avatar":"🚕","emotion":"friendly","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'destination-choice', 2, 'choice',
    'George', 'Choose the correct destination request.', 'Ви їдете до British Museum.',
    '[{"id":"museum","text":"Please take me to the British Museum.","value":"museum"},{"id":"medicine","text":"I need some painkillers.","value":"medicine"},{"id":"parcel","text":"I would like to send this parcel.","value":"parcel"}]'::jsonb, '{"optionId":"museum"}'::jsonb,
    'address-question', '{}'::jsonb,
    '{"mode":"exact","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Правильно! Ви чітко назвали місце призначення.","feedbackIncorrect":"Оберіть фразу про British Museum."}'::jsonb, '{"role":"Taxi driver","avatar":"🚕","emotion":"neutral","goal":"state destination","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'address-question', 3, 'dialogue',
    'George', 'Do you have the exact address?', null,
    '[]'::jsonb, null,
    'address-input', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Taxi driver","avatar":"🚕","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'address-input', 4, 'input',
    'George', 'What is the address?', 'Напишіть адресу: Great Russell Street.',
    '[]'::jsonb, '{"acceptedAnswers":["Great Russell Street","It is on Great Russell Street","It''s on Great Russell Street"]}'::jsonb,
    'time-translate', '{}'::jsonb,
    '{"mode":"case_insensitive","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Добре! Ви надали адресу.","feedbackIncorrect":"Спробуйте: Great Russell Street."}'::jsonb, '{"role":"Taxi driver","avatar":"🚕","emotion":"neutral","goal":"give address","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'time-translate', 5, 'translate',
    'Емма', 'Скільки часу займе поїздка?', 'Перекладіть англійською.',
    '[]'::jsonb, '{"acceptedAnswers":["How long will the journey take","How long will the journey take?","How long will it take","How long will it take?"]}'::jsonb,
    'time-answer', '{}'::jsonb,
    '{"mode":"case_insensitive","points":15,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Чудово! Це природне запитання про тривалість.","feedbackIncorrect":"Спробуйте: How long will it take?"}'::jsonb, '{"role":"Ваш наставник","avatar":"🙂","emotion":"neutral","goal":"ask journey time","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'time-answer', 6, 'dialogue',
    'George', 'It should take about twenty minutes, depending on traffic.', null,
    '[]'::jsonb, null,
    'traffic-choice', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Taxi driver","avatar":"🚕","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'traffic-choice', 7, 'choice',
    'George', 'What may change the journey time?', 'Оберіть правильну відповідь.',
    '[{"id":"traffic","text":"Traffic.","value":"traffic"},{"id":"breakfast","text":"Breakfast.","value":"breakfast"},{"id":"passport","text":"A passport.","value":"passport"}]'::jsonb, '{"optionId":"traffic"}'::jsonb,
    'route-dialogue', '{}'::jsonb,
    '{"mode":"exact","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Так, час залежить від дорожнього руху.","feedbackIncorrect":"Оберіть Traffic."}'::jsonb, '{"role":"Taxi driver","avatar":"🚕","emotion":"neutral","goal":"understand traffic","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'route-dialogue', 8, 'dialogue',
    'George', 'There is heavy traffic ahead. I can take a different route.', null,
    '[]'::jsonb, null,
    'route-input', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Taxi driver","avatar":"🚕","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'route-input', 9, 'input',
    'George', 'Would you like me to take a different route?', 'Погодьтеся на інший маршрут.',
    '[]'::jsonb, '{"acceptedAnswers":["Yes please take a different route","Yes, please take a different route","Yes that is fine","Yes, that is fine"]}'::jsonb,
    'price-dialogue', '{}'::jsonb,
    '{"mode":"case_insensitive","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Правильно! Ви погодилися змінити маршрут.","feedbackIncorrect":"Спробуйте: Yes, please take a different route."}'::jsonb, '{"role":"Taxi driver","avatar":"🚕","emotion":"neutral","goal":"approve alternate route","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'price-dialogue', 10, 'dialogue',
    'George', 'We are almost there. The fare is eighteen pounds.', null,
    '[]'::jsonb, null,
    'fare-translate', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Taxi driver","avatar":"🚕","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'fare-translate', 11, 'translate',
    'Емма', 'Чи можу я заплатити карткою?', 'Перекладіть англійською.',
    '[]'::jsonb, '{"acceptedAnswers":["Can I pay by card","Can I pay by card?","Could I pay by card","Could I pay by card?"]}'::jsonb,
    'card-answer', '{}'::jsonb,
    '{"mode":"case_insensitive","points":15,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Відмінно! Ви уточнили спосіб оплати.","feedbackIncorrect":"Спробуйте: Can I pay by card?"}'::jsonb, '{"role":"Ваш наставник","avatar":"🙂","emotion":"neutral","goal":"ask card payment","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'card-answer', 12, 'dialogue',
    'George', 'Yes, card is fine.', null,
    '[]'::jsonb, null,
    'receipt-choice', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Taxi driver","avatar":"🚕","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'receipt-choice', 13, 'choice',
    'George', 'Would you like a receipt?', 'Вам потрібна квитанція.',
    '[{"id":"receipt","text":"Yes, please.","value":"receipt"},{"id":"platform","text":"Platform three, please.","value":"platform"},{"id":"prescription","text":"Do I need a prescription?","value":"prescription"}]'::jsonb, '{"optionId":"receipt"}'::jsonb,
    'final-dialogue', '{}'::jsonb,
    '{"mode":"exact","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Так, це ввічлива коротка відповідь.","feedbackIncorrect":"Оберіть Yes, please."}'::jsonb, '{"role":"Taxi driver","avatar":"🚕","emotion":"neutral","goal":"request receipt","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'final-dialogue', 14, 'dialogue',
    'George', 'Here is your receipt. Have a great day!', null,
    '[]'::jsonb, null,
    'summary', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Taxi driver","avatar":"🚕","emotion":"happy","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'summary', 15, 'completion',
    'Емма', 'Ви назвали місце й адресу, уточнили тривалість, погодили маршрут, оплатили поїздку та отримали квитанцію.', null,
    '[]'::jsonb, null,
    null, '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"Ваш наставник","avatar":"🎉","emotion":"celebrating","goal":"","learnedWords":["destination","address","traffic","route","fare","pay by card","receipt"]}'::jsonb
  );
end $$;
