-- Generated by TalkHero Quest Authoring System v1

-- Generated quest: At the Restaurant
do $$
declare
  campaign_uuid uuid;
  episode_uuid uuid;
  quest_uuid uuid;
  act_uuid uuid;
begin
  select id into campaign_uuid from public.quest_campaigns
  where slug = 'english-basics' and status = 'published';
  if campaign_uuid is null then raise exception 'Campaign not found: english-basics'; end if;

  select id into episode_uuid from public.quest_episodes
  where campaign_id = campaign_uuid and slug = 'first-contact' and status = 'published';
  if episode_uuid is null then raise exception 'Episode not found: first-contact'; end if;

  select id into quest_uuid from public.quests
  where episode_id = episode_uuid and slug = 'restaurant';

  if quest_uuid is null then
    insert into public.quests (
      episode_id, slug, title, description, quest_type, cefr_level,
      order_index, estimated_minutes, xp_reward, coin_reward, status, config, metadata
    ) values (
      episode_uuid, 'restaurant', 'At the Restaurant', 'Reserve a table, order a meal, ask about ingredients and request the bill.',
      'conversation', 'A2', 4, 12,
      75, 25, 'published', '{"version":1,"sceneCount":16,"staticTest":true,"generated":true}'::jsonb, '{"templateCategory":"food","staticTest":true,"staticQuest":true,"generatedBy":"TalkHero Quest Authoring System v1","adventure":"london-first-day","location":"restaurant"}'::jsonb
    ) returning id into quest_uuid;
  else
    update public.quests set
      title='At the Restaurant', description='Reserve a table, order a meal, ask about ingredients and request the bill.', quest_type='conversation',
      cefr_level='A2', order_index=4,
      estimated_minutes=12, xp_reward=75, coin_reward=25,
      status='published', config='{"version":1,"sceneCount":16,"staticTest":true,"generated":true}'::jsonb,
      metadata=coalesce(metadata,'{}'::jsonb)||'{"templateCategory":"food","staticTest":true,"staticQuest":true,"generatedBy":"TalkHero Quest Authoring System v1","adventure":"london-first-day","location":"restaurant"}'::jsonb, updated_at=now()
    where id=quest_uuid;
  end if;

  select id into act_uuid from public.quest_acts
  where quest_id=quest_uuid and act_code='main';

  if act_uuid is null then
    insert into public.quest_acts (
      quest_id, act_code, title, description, order_index, status, checkpoint, metadata
    ) values (
      quest_uuid, 'main', 'Dinner in London', 'Speak with the waiter and complete your meal.',
      0, 'published', false, '{"generated":true}'::jsonb
    ) returning id into act_uuid;
  else
    update public.quest_acts set
      title='Dinner in London', description='Speak with the waiter and complete your meal.',
      status='published', updated_at=now()
    where id=act_uuid;
  end if;

  delete from public.quest_scenes where quest_id=quest_uuid;

  insert into public.quest_scenes (
    quest_id, act_id, scene_code, order_index, scene_type, speaker,
    content, prompt, options, expected_answer, next_scene_code,
    branching, evaluation_config, metadata
  ) values
  (
    quest_uuid, act_uuid, 'intro', 0, 'narration',
    'Емма', 'Ви прийшли до ресторану. Потрібно отримати столик, зробити замовлення, уточнити склад страви та попросити рахунок.', null,
    '[]'::jsonb, null,
    'waiter-greeting', '{}'::jsonb,
    '{}'::jsonb, '{"role":"Ваш наставник","avatar":"🙂","emotion":"encouraging"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'waiter-greeting', 1, 'dialogue',
    'James', 'Good evening. Do you have a reservation?', null,
    '[]'::jsonb, null,
    'reservation-choice', '{}'::jsonb,
    '{}'::jsonb, '{"role":"Waiter","avatar":"🍽️","emotion":"friendly"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'reservation-choice', 2, 'choice',
    'James', 'Choose the correct response.', 'У вас немає бронювання.',
    '[{"id":"no-reservation","text":"No, I don''t. Do you have a table for one?","value":"no-reservation"},{"id":"hotel","text":"I have a hotel reservation.","value":"hotel"},{"id":"airport","text":"Where is gate B16?","value":"airport"}]'::jsonb, '{"optionId":"no-reservation"}'::jsonb,
    'table-dialogue', '{}'::jsonb,
    '{"mode":"exact","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Правильно! Ви чітко пояснили, що не маєте бронювання.","feedbackIncorrect":"Оберіть фразу про столик без бронювання."}'::jsonb, '{"role":"Waiter","avatar":"🍽️","goal":"ask for a table"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'table-dialogue', 3, 'dialogue',
    'James', 'Certainly. Please follow me. Here is the menu.', null,
    '[]'::jsonb, null,
    'starter-input', '{}'::jsonb,
    '{}'::jsonb, '{"role":"Waiter","avatar":"🍽️"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'starter-input', 4, 'input',
    'James', 'Would you like a starter?', 'Напишіть, що ви хотіли б томатний суп.',
    '[]'::jsonb, '{"acceptedAnswers":["I would like the tomato soup","I''d like the tomato soup","The tomato soup please","Tomato soup please"]}'::jsonb,
    'main-dialogue', '{}'::jsonb,
    '{"mode":"case_insensitive","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Чудово! Ви природно замовили першу страву.","feedbackIncorrect":"Спробуйте: I''d like the tomato soup."}'::jsonb, '{"role":"Waiter","avatar":"🍽️","goal":"order a starter"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'main-dialogue', 5, 'dialogue',
    'James', 'And what would you like for your main course?', null,
    '[]'::jsonb, null,
    'main-choice', '{}'::jsonb,
    '{}'::jsonb, '{"role":"Waiter","avatar":"🍽️"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'main-choice', 6, 'choice',
    'James', 'Choose a polite main-course order.', 'Ви хочете курку з овочами.',
    '[{"id":"chicken","text":"Could I have the chicken with vegetables, please?","value":"chicken"},{"id":"ticket","text":"A single ticket, please.","value":"ticket"},{"id":"room","text":"I need a room for one night.","value":"room"}]'::jsonb, '{"optionId":"chicken"}'::jsonb,
    'allergy-dialogue', '{}'::jsonb,
    '{"mode":"exact","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Правильно! Це ввічливе замовлення основної страви.","feedbackIncorrect":"Оберіть фразу про курку з овочами."}'::jsonb, '{"role":"Waiter","avatar":"🍽️","goal":"order main course"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'allergy-dialogue', 7, 'dialogue',
    'James', 'Of course. Do you have any allergies?', null,
    '[]'::jsonb, null,
    'allergy-translate', '{}'::jsonb,
    '{}'::jsonb, '{"role":"Waiter","avatar":"🍽️"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'allergy-translate', 8, 'translate',
    'Емма', 'У мене алергія на горіхи.', 'Перекладіть англійською.',
    '[]'::jsonb, '{"acceptedAnswers":["I am allergic to nuts","I''m allergic to nuts","I have a nut allergy"]}'::jsonb,
    'drink-dialogue', '{}'::jsonb,
    '{"mode":"case_insensitive","points":15,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Відмінно! Ви правильно повідомили про алергію.","feedbackIncorrect":"Спробуйте: I''m allergic to nuts."}'::jsonb, '{"role":"Ваш наставник","avatar":"🙂","goal":"state allergy"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'drink-dialogue', 9, 'dialogue',
    'James', 'Thank you for telling me. What would you like to drink?', null,
    '[]'::jsonb, null,
    'drink-input', '{}'::jsonb,
    '{}'::jsonb, '{"role":"Waiter","avatar":"🍽️"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'drink-input', 10, 'input',
    'James', 'What would you like to drink?', 'Замовте негазовану воду.',
    '[]'::jsonb, '{"acceptedAnswers":["Still water please","Still water, please","I would like still water","I''d like still water"]}'::jsonb,
    'dessert-dialogue', '{}'::jsonb,
    '{"mode":"case_insensitive","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Добре! Still water означає негазовану воду.","feedbackIncorrect":"Спробуйте: Still water, please."}'::jsonb, '{"role":"Waiter","avatar":"🍽️","goal":"order a drink"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'dessert-dialogue', 11, 'dialogue',
    'James', 'Would you like to see the dessert menu?', null,
    '[]'::jsonb, null,
    'dessert-choice', '{}'::jsonb,
    '{}'::jsonb, '{"role":"Waiter","avatar":"🍽️"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'dessert-choice', 12, 'choice',
    'James', 'Choose a polite refusal.', 'Ви не хочете десерт.',
    '[{"id":"no-dessert","text":"No, thank you. I''m full.","value":"no-dessert"},{"id":"platform","text":"Which platform is it?","value":"platform"},{"id":"passport","text":"Here is my passport.","value":"passport"}]'::jsonb, '{"optionId":"no-dessert"}'::jsonb,
    'bill-translate', '{}'::jsonb,
    '{"mode":"exact","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Чудово! Ви ввічливо відмовилися.","feedbackIncorrect":"Оберіть No, thank you. I''m full."}'::jsonb, '{"role":"Waiter","avatar":"🍽️","goal":"decline dessert"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'bill-translate', 13, 'translate',
    'Емма', 'Можна рахунок, будь ласка?', 'Перекладіть англійською.',
    '[]'::jsonb, '{"acceptedAnswers":["Can I have the bill please","Can I have the bill, please","Could I have the bill please","Could I have the bill, please","The bill please","The bill, please"]}'::jsonb,
    'final-dialogue', '{}'::jsonb,
    '{"mode":"case_insensitive","points":15,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Правильно! Це стандартне прохання принести рахунок.","feedbackIncorrect":"Спробуйте: Could I have the bill, please?"}'::jsonb, '{"role":"Ваш наставник","avatar":"🙂","goal":"ask for the bill"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'final-dialogue', 14, 'dialogue',
    'James', 'Certainly. Here is your bill. Thank you for visiting us!', null,
    '[]'::jsonb, null,
    'summary', '{}'::jsonb,
    '{}'::jsonb, '{"role":"Waiter","avatar":"🍽️","emotion":"happy"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'summary', 15, 'completion',
    'Емма', 'Ви отримали столик, замовили страви й напій, повідомили про алергію та попросили рахунок.', null,
    '[]'::jsonb, null,
    null, '{}'::jsonb,
    '{}'::jsonb, '{"role":"Ваш наставник","avatar":"🎉","emotion":"celebrating","learnedWords":["reservation","starter","main course","allergic","still water","dessert","bill"]}'::jsonb
  );
end $$;

-- Generated quest: At the Supermarket
do $$
declare
  campaign_uuid uuid;
  episode_uuid uuid;
  quest_uuid uuid;
  act_uuid uuid;
begin
  select id into campaign_uuid from public.quest_campaigns
  where slug = 'english-basics' and status = 'published';
  if campaign_uuid is null then raise exception 'Campaign not found: english-basics'; end if;

  select id into episode_uuid from public.quest_episodes
  where campaign_id = campaign_uuid and slug = 'first-contact' and status = 'published';
  if episode_uuid is null then raise exception 'Episode not found: first-contact'; end if;

  select id into quest_uuid from public.quests
  where episode_id = episode_uuid and slug = 'supermarket';

  if quest_uuid is null then
    insert into public.quests (
      episode_id, slug, title, description, quest_type, cefr_level,
      order_index, estimated_minutes, xp_reward, coin_reward, status, config, metadata
    ) values (
      episode_uuid, 'supermarket', 'At the Supermarket', 'Find products, ask about prices, understand quantities and pay at the checkout.',
      'conversation', 'A1', 5, 10,
      65, 22, 'published', '{"version":1,"sceneCount":16,"staticTest":true,"generated":true}'::jsonb, '{"templateCategory":"shopping","staticTest":true,"staticQuest":true,"generatedBy":"TalkHero Quest Authoring System v1","adventure":"london-first-day","location":"supermarket"}'::jsonb
    ) returning id into quest_uuid;
  else
    update public.quests set
      title='At the Supermarket', description='Find products, ask about prices, understand quantities and pay at the checkout.', quest_type='conversation',
      cefr_level='A1', order_index=5,
      estimated_minutes=10, xp_reward=65, coin_reward=22,
      status='published', config='{"version":1,"sceneCount":16,"staticTest":true,"generated":true}'::jsonb,
      metadata=coalesce(metadata,'{}'::jsonb)||'{"templateCategory":"shopping","staticTest":true,"staticQuest":true,"generatedBy":"TalkHero Quest Authoring System v1","adventure":"london-first-day","location":"supermarket"}'::jsonb, updated_at=now()
    where id=quest_uuid;
  end if;

  select id into act_uuid from public.quest_acts
  where quest_id=quest_uuid and act_code='main';

  if act_uuid is null then
    insert into public.quest_acts (
      quest_id, act_code, title, description, order_index, status, checkpoint, metadata
    ) values (
      quest_uuid, 'main', 'Shopping for groceries', 'Find everything on your shopping list and pay.',
      0, 'published', false, '{"generated":true}'::jsonb
    ) returning id into act_uuid;
  else
    update public.quest_acts set
      title='Shopping for groceries', description='Find everything on your shopping list and pay.',
      status='published', updated_at=now()
    where id=act_uuid;
  end if;

  delete from public.quest_scenes where quest_id=quest_uuid;

  insert into public.quest_scenes (
    quest_id, act_id, scene_code, order_index, scene_type, speaker,
    content, prompt, options, expected_answer, next_scene_code,
    branching, evaluation_config, metadata
  ) values
  (
    quest_uuid, act_uuid, 'intro', 0, 'narration',
    'Емма', 'Ви зайшли до супермаркету. Потрібно знайти продукти, уточнити ціну й кількість та оплатити покупки.', null,
    '[]'::jsonb, null,
    'assistant-greeting', '{}'::jsonb,
    '{}'::jsonb, '{"role":"Ваш наставник","avatar":"🙂","emotion":"encouraging"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'assistant-greeting', 1, 'dialogue',
    'Grace', 'Hello. Can I help you find something?', null,
    '[]'::jsonb, null,
    'bread-choice', '{}'::jsonb,
    '{}'::jsonb, '{"role":"Shop assistant","avatar":"🛒","emotion":"friendly"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'bread-choice', 2, 'choice',
    'Grace', 'Choose the correct way to ask for bread.', 'Ви шукаєте хліб.',
    '[{"id":"bread","text":"Excuse me, where can I find the bread?","value":"bread"},{"id":"hotel","text":"I have a hotel reservation.","value":"hotel"},{"id":"airport","text":"When does boarding start?","value":"airport"}]'::jsonb, '{"optionId":"bread"}'::jsonb,
    'aisle-dialogue', '{}'::jsonb,
    '{"mode":"exact","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Правильно! Це ввічливе запитання про розташування товару.","feedbackIncorrect":"Оберіть фразу про хліб."}'::jsonb, '{"role":"Shop assistant","avatar":"🛒","goal":"find bread"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'aisle-dialogue', 3, 'dialogue',
    'Grace', 'The bread is in aisle five, next to the bakery.', null,
    '[]'::jsonb, null,
    'aisle-choice', '{}'::jsonb,
    '{}'::jsonb, '{"role":"Shop assistant","avatar":"🛒"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'aisle-choice', 4, 'choice',
    'Grace', 'Which aisle should you go to?', 'Оберіть правильний прохід.',
    '[{"id":"five","text":"Aisle five.","value":"five"},{"id":"four","text":"Aisle four.","value":"four"},{"id":"six","text":"Aisle six.","value":"six"}]'::jsonb, '{"optionId":"five"}'::jsonb,
    'milk-input', '{}'::jsonb,
    '{"mode":"exact","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Так, хліб знаходиться в проході номер п’ять.","feedbackIncorrect":"Оберіть Aisle five."}'::jsonb, '{"role":"Shop assistant","avatar":"🛒","goal":"understand aisle"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'milk-input', 5, 'input',
    'Grace', 'Do you need anything else?', 'Запитайте, де знаходиться молоко.',
    '[]'::jsonb, '{"acceptedAnswers":["Where is the milk","Where can I find the milk","Could you tell me where the milk is"]}'::jsonb,
    'milk-dialogue', '{}'::jsonb,
    '{"mode":"case_insensitive","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Добре! Ви правильно запитали про молоко.","feedbackIncorrect":"Спробуйте: Where can I find the milk?"}'::jsonb, '{"role":"Shop assistant","avatar":"🛒","goal":"find milk"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'milk-dialogue', 6, 'dialogue',
    'Grace', 'It is in the refrigerated section at the back of the store.', null,
    '[]'::jsonb, null,
    'quantity-translate', '{}'::jsonb,
    '{}'::jsonb, '{"role":"Shop assistant","avatar":"🛒"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'quantity-translate', 7, 'translate',
    'Емма', 'Мені потрібні два літри молока.', 'Перекладіть англійською.',
    '[]'::jsonb, '{"acceptedAnswers":["I need two litres of milk","I need two liters of milk","Two litres of milk please","Two liters of milk please"]}'::jsonb,
    'price-dialogue', '{}'::jsonb,
    '{"mode":"case_insensitive","points":15,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Чудово! Ви правильно назвали кількість.","feedbackIncorrect":"Спробуйте: I need two litres of milk."}'::jsonb, '{"role":"Ваш наставник","avatar":"🙂","goal":"state quantity"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'price-dialogue', 8, 'dialogue',
    'Grace', 'This brand is on special offer today.', null,
    '[]'::jsonb, null,
    'price-input', '{}'::jsonb,
    '{}'::jsonb, '{"role":"Shop assistant","avatar":"🛒"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'price-input', 9, 'input',
    'Grace', 'Would you like to know the price?', 'Запитайте, скільки це коштує.',
    '[]'::jsonb, '{"acceptedAnswers":["How much is it","How much does it cost","What is the price","What''s the price"]}'::jsonb,
    'price-answer', '{}'::jsonb,
    '{"mode":"case_insensitive","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Правильно! Це природне запитання про ціну.","feedbackIncorrect":"Спробуйте: How much is it?"}'::jsonb, '{"role":"Shop assistant","avatar":"🛒","goal":"ask price"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'price-answer', 10, 'dialogue',
    'Grace', 'It is two pounds fifty.', null,
    '[]'::jsonb, null,
    'checkout-choice', '{}'::jsonb,
    '{}'::jsonb, '{"role":"Shop assistant","avatar":"🛒"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'checkout-choice', 11, 'choice',
    'Cashier', 'Would you like a bag?', 'Вам потрібен пакет.',
    '[{"id":"bag","text":"Yes, please.","value":"bag"},{"id":"platform","text":"Platform four, please.","value":"platform"},{"id":"room","text":"A single room, please.","value":"room"}]'::jsonb, '{"optionId":"bag"}'::jsonb,
    'payment-dialogue', '{}'::jsonb,
    '{"mode":"exact","points":10,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Так, це коротка й ввічлива відповідь.","feedbackIncorrect":"Оберіть Yes, please."}'::jsonb, '{"role":"Cashier","avatar":"🧾","goal":"request a bag"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'payment-dialogue', 12, 'dialogue',
    'Cashier', 'That will be twelve pounds eighty. Cash or card?', null,
    '[]'::jsonb, null,
    'payment-translate', '{}'::jsonb,
    '{}'::jsonb, '{"role":"Cashier","avatar":"🧾"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'payment-translate', 13, 'translate',
    'Емма', 'Я заплачу карткою.', 'Перекладіть англійською.',
    '[]'::jsonb, '{"acceptedAnswers":["I will pay by card","I''ll pay by card","By card please","By card, please"]}'::jsonb,
    'final-dialogue', '{}'::jsonb,
    '{"mode":"case_insensitive","points":15,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Відмінно! Ви правильно назвали спосіб оплати.","feedbackIncorrect":"Спробуйте: I''ll pay by card."}'::jsonb, '{"role":"Ваш наставник","avatar":"🙂","goal":"pay by card"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'final-dialogue', 14, 'dialogue',
    'Cashier', 'Payment approved. Here is your receipt. Have a nice day!', null,
    '[]'::jsonb, null,
    'summary', '{}'::jsonb,
    '{}'::jsonb, '{"role":"Cashier","avatar":"🧾","emotion":"happy"}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'summary', 15, 'completion',
    'Емма', 'Ви знайшли потрібні продукти, уточнили кількість і ціну, попросили пакет та оплатили покупки.', null,
    '[]'::jsonb, null,
    null, '{}'::jsonb,
    '{}'::jsonb, '{"role":"Ваш наставник","avatar":"🎉","emotion":"celebrating","learnedWords":["aisle","bakery","refrigerated section","litre","special offer","receipt"]}'::jsonb
  );
end $$;
