-- Generated by TalkHero Quest Authoring System v1

-- Generated quest: At the Bank
do $$
declare
  campaign_uuid uuid;
  episode_uuid uuid;
  quest_uuid uuid;
  act_uuid uuid;
begin
  select id into campaign_uuid from public.quest_campaigns
  where slug = 'english-basics' and status = 'published';
  if campaign_uuid is null then raise exception 'Campaign not found: english-basics'; end if;

  select id into episode_uuid from public.quest_episodes
  where campaign_id = campaign_uuid and slug = 'first-contact' and status = 'published';
  if episode_uuid is null then raise exception 'Episode not found: first-contact'; end if;

  select id into quest_uuid from public.quests
  where episode_id = episode_uuid and slug = 'bank';

  if quest_uuid is null then
    insert into public.quests (
      episode_id, slug, title, description, quest_type, cefr_level,
      order_index, estimated_minutes, xp_reward, coin_reward, status, config, metadata
    ) values (
      episode_uuid, 'bank', 'At the Bank', 'Learn to exchange money politely and understand key conditions at the bank.',
      'conversation', 'A2', 6, 12,
      75, 25, 'published', '{"version":1,"sceneCount":15,"staticTest":true,"generated":true}'::jsonb, '{"templateCategory":"static","staticTest":true,"staticQuest":true,"generatedBy":"TalkHero Quest Authoring System v1","adventure":"london-first-day","location":"London"}'::jsonb
    ) returning id into quest_uuid;
  else
    update public.quests set
      title='At the Bank', description='Learn to exchange money politely and understand key conditions at the bank.', quest_type='conversation',
      cefr_level='A2', order_index=6,
      estimated_minutes=12, xp_reward=75, coin_reward=25,
      status='published', config='{"version":1,"sceneCount":15,"staticTest":true,"generated":true}'::jsonb,
      metadata=coalesce(metadata,'{}'::jsonb)||'{"templateCategory":"static","staticTest":true,"staticQuest":true,"generatedBy":"TalkHero Quest Authoring System v1","adventure":"london-first-day","location":"London"}'::jsonb, updated_at=now()
    where id=quest_uuid;
  end if;

  select id
  into act_uuid
  from public.quest_acts
  where quest_id = quest_uuid
  order by order_index
  limit 1;

  if act_uuid is null then
    insert into public.quest_acts (
      quest_id, act_code, title, description, order_index, status, checkpoint, metadata
    ) values (
      quest_uuid, 'bank-services', 'Bank Services', 'Engage with bank services for currency exchange.',
      0, 'published', false, '{"generated":true}'::jsonb
    ) returning id into act_uuid;
  else
    update public.quest_acts
    set
      act_code = 'bank-services',
      title = 'Bank Services',
      description = 'Engage with bank services for currency exchange.',
      order_index = 0,
      status = 'published',
      updated_at = now()
    where id = act_uuid;
  end if;

  delete from public.quest_scenes where quest_id=quest_uuid;

  insert into public.quest_scenes (
    quest_id, act_id, scene_code, order_index, scene_type, speaker,
    content, prompt, options, expected_answer, next_scene_code,
    branching, evaluation_config, metadata
  ) values
  (
    quest_uuid, act_uuid, 'narration-1', 0, 'narration',
    null, 'You walk into a London bank, looking to exchange some money.', null,
    '[]'::jsonb, null,
    'dialogue-1', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"","avatar":"рџ’¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'dialogue-1', 1, 'dialogue',
    'Olivia', 'Hello! How can I assist you today?', null,
    '[]'::jsonb, null,
    'input-1', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"","avatar":"рџ’¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'input-1', 2, 'input',
    null, 'Hello! How can I assist you today?', 'Напишіть англійською, що ви хочете обміняти гроші.',
    '[]'::jsonb, '{"acceptedAnswers":["I would like to exchange some money, please.","I''d like to exchange some money."]}'::jsonb,
    'dialogue-2', '{}'::jsonb,
    '{"mode":"case_insensitive","points":1,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Чудово! Конструкція “I''d like to...” звучить ввічливо й природно для подібних ситуацій.","feedbackIncorrect":"Природніше англійською: I''d like to exchange some money, please.\n\nЧому саме так: “I''d like to...” є ввічливим способом висловити бажання, щоб вам допомогли.\n\nЗапам''ятайте: “I''d like to...” — універсальний початок ввічливого прохання."}'::jsonb, '{"role":"","avatar":"рџ’¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'dialogue-2', 3, 'dialogue',
    'Olivia', 'Sure! What currency would you like to exchange?', null,
    '[]'::jsonb, null,
    'input-2', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"","avatar":"рџ’¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'input-2', 4, 'input',
    null, 'Sure! What currency would you like to exchange?', 'Напишіть англійською, що ви хочете обміняти євро.',
    '[]'::jsonb, '{"acceptedAnswers":["I would like to change my euros.","I''d like to exchange my euros."]}'::jsonb,
    'dialogue-3', '{}'::jsonb,
    '{"mode":"case_insensitive","points":1,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Чудово! Ви правильно використовуєте конструкцію “I''d like to...” для ввічливого запиту.","feedbackIncorrect":"Природніше англійською: I''d like to exchange my euros.\n\nЧому саме так: “Exchange” є кращим словом для всіх операцій з валютою в банку.\n\nЗапам''ятайте: “I''d like to exchange...” — ввічливий початок запиту на обмін."}'::jsonb, '{"role":"","avatar":"рџ’¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'dialogue-3', 5, 'dialogue',
    'Olivia', 'Great! Do you have an identification?', null,
    '[]'::jsonb, null,
    'input-3', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"","avatar":"рџ’¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'input-3', 6, 'input',
    null, 'Great! Do you have an identification?', 'Напишіть англійською, що ви передаєте своє посвідчення.',
    '[]'::jsonb, '{"acceptedAnswers":["Yes, here is my identification.","Here is my ID."]}'::jsonb,
    'dialogue-4', '{}'::jsonb,
    '{"mode":"case_insensitive","points":1,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Чудово! “Here is my identification.” звучить ввічливо й ясно в таких ситуаціях.","feedbackIncorrect":"Природніше англійською: Here is my ID.\n\nЧому саме так: “ID” це звична абревіатура для документа, який підтверджує особу, простіша в використанні.\n\nЗапам''ятайте: “Here is my ID.” — природний спосіб передати документ."}'::jsonb, '{"role":"","avatar":"рџ’¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'dialogue-4', 7, 'dialogue',
    'Olivia', 'Thank you! Now, let me check the exchange rate and fees for you.', null,
    '[]'::jsonb, null,
    'narration-2', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"","avatar":"рџ’¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'narration-2', 8, 'narration',
    null, 'While you wait, you think about the fees for exchanging money.', null,
    '[]'::jsonb, null,
    'dialogue-5', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"","avatar":"рџ’¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'dialogue-5', 9, 'dialogue',
    'Olivia', 'The exchange rate today is 1 euro to 1.15 pounds, and the fee is 2% of the amount.', null,
    '[]'::jsonb, null,
    'input-4', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"","avatar":"рџ’¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'input-4', 10, 'input',
    null, 'The exchange rate today is 1 euro to 1.15 pounds, and the fee is 2% of the amount.', 'Запитайте про розмір комісії.',
    '[]'::jsonb, '{"acceptedAnswers":["How much will the fee be?","How much is the fee?"]}'::jsonb,
    'dialogue-6', '{}'::jsonb,
    '{"mode":"case_insensitive","points":1,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Чудово! Питання “How much will the fee be?” є природним і цілеспрямованим.","feedbackIncorrect":"Природніше англійською: How much will the fee be?\n\nЧому саме так: Це пряма форма запитання допомагає отримати точну інформацію про витрати.\n\nЗапам''ятайте: “How much is the fee?” — просте питання для уточнення витрат."}'::jsonb, '{"role":"","avatar":"рџ’¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'dialogue-6', 11, 'dialogue',
    'Olivia', 'The fee will be 2 pounds for 100 euros.', null,
    '[]'::jsonb, null,
    'input-5', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"","avatar":"рџ’¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'input-5', 12, 'input',
    null, 'The fee will be 2 pounds for 100 euros.', 'Напишіть англійською, що ви хочете підтвердити транзакцію.',
    '[]'::jsonb, '{"acceptedAnswers":["I would like to confirm the transaction.","I''d like to confirm the transaction."]}'::jsonb,
    'dialogue-7', '{}'::jsonb,
    '{"mode":"case_insensitive","points":1,"allowRetry":true,"maxAttempts":2,"feedbackCorrect":"Чудово! “I''d like to confirm the transaction.” — ввічливий і чіткий спосіб підтвердити вашу угоду.","feedbackIncorrect":"Природніше англійською: I''d like to confirm the transaction.\n\nЧому саме так: “I''d like to...” забезпечує ввічливе звучання вашого підтвердження, підкреслюючи вашу серйозність.\n\nЗапам''ятайте: “I''d like to confirm...” — ввічливий спосіб висловити вашу згоду."}'::jsonb, '{"role":"","avatar":"рџ’¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'dialogue-7', 13, 'dialogue',
    'Olivia', 'Thank you! Here is your receipt. Have a great day!', null,
    '[]'::jsonb, null,
    'summary', '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"","avatar":"рџ’¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  ),
  (
    quest_uuid, act_uuid, 'summary', 14, 'completion',
    null, 'You have successfully completed the transaction and exchanged your euros. You feel pleased with your experience at the bank.', null,
    '[]'::jsonb, null,
    null, '{}'::jsonb,
    '{"mode":"manual","points":0,"allowRetry":false,"maxAttempts":1,"feedbackCorrect":"","feedbackIncorrect":""}'::jsonb, '{"role":"","avatar":"рџ’¬","emotion":"neutral","goal":"","learnedWords":[]}'::jsonb
  );
end $$;
